<?php

use Illuminate\Database\Seeder;

class CitiesTableRNSeeder extends Seeder
{
    /**
     * Alimenta um schema de cities com as cities do Rio Grande do Norte
     * @author Cesar André (https://github.com/cesar-andre)
     * @return void
     */
    public function run()
    {
    	DB::table('cities')->insert(['id' => 2400109, 'states_id' => 24, 'name' => 'Acari']);
		DB::table('cities')->insert(['id' => 2400208, 'states_id' => 24, 'name' => 'Açu']);
		DB::table('cities')->insert(['id' => 2400307, 'states_id' => 24, 'name' => 'Afonso Bezerra']);
		DB::table('cities')->insert(['id' => 2400406, 'states_id' => 24, 'name' => 'Água Nova']);
		DB::table('cities')->insert(['id' => 2400505, 'states_id' => 24, 'name' => 'Alexandria']);
		DB::table('cities')->insert(['id' => 2400604, 'states_id' => 24, 'name' => 'Almino Afonso']);
		DB::table('cities')->insert(['id' => 2400703, 'states_id' => 24, 'name' => 'Alto do Rodrigues']);
		DB::table('cities')->insert(['id' => 2400802, 'states_id' => 24, 'name' => 'Angicos']);
		DB::table('cities')->insert(['id' => 2400901, 'states_id' => 24, 'name' => 'Antônio Martins']);
		DB::table('cities')->insert(['id' => 2401008, 'states_id' => 24, 'name' => 'Apodi']);
		DB::table('cities')->insert(['id' => 2401107, 'states_id' => 24, 'name' => 'Areia Branca']);
		DB::table('cities')->insert(['id' => 2401206, 'states_id' => 24, 'name' => 'Arês']);
		DB::table('cities')->insert(['id' => 2401305, 'states_id' => 24, 'name' => 'Augusto Severo']);
		DB::table('cities')->insert(['id' => 2401404, 'states_id' => 24, 'name' => 'Baía Formosa']);
		DB::table('cities')->insert(['id' => 2401453, 'states_id' => 24, 'name' => 'Baraúna']);
		DB::table('cities')->insert(['id' => 2401503, 'states_id' => 24, 'name' => 'Barcelona']);
		DB::table('cities')->insert(['id' => 2401602, 'states_id' => 24, 'name' => 'Bento Fernandes']);
		DB::table('cities')->insert(['id' => 2401651, 'states_id' => 24, 'name' => 'Bodó']);
		DB::table('cities')->insert(['id' => 2401701, 'states_id' => 24, 'name' => 'Bom Jesus']);
		DB::table('cities')->insert(['id' => 2401800, 'states_id' => 24, 'name' => 'Brejinho']);
		DB::table('cities')->insert(['id' => 2401859, 'states_id' => 24, 'name' => 'Caiçara do Norte']);
		DB::table('cities')->insert(['id' => 2401909, 'states_id' => 24, 'name' => 'Caiçara do Rio do Vento']);
		DB::table('cities')->insert(['id' => 2402006, 'states_id' => 24, 'name' => 'Caicó']);
		DB::table('cities')->insert(['id' => 2402105, 'states_id' => 24, 'name' => 'Campo Redondo']);
		DB::table('cities')->insert(['id' => 2402204, 'states_id' => 24, 'name' => 'Canguaretama']);
		DB::table('cities')->insert(['id' => 2402303, 'states_id' => 24, 'name' => 'Caraúbas']);
		DB::table('cities')->insert(['id' => 2402402, 'states_id' => 24, 'name' => 'Carnaúba dos Dantas']);
		DB::table('cities')->insert(['id' => 2402501, 'states_id' => 24, 'name' => 'Carnaubais']);
		DB::table('cities')->insert(['id' => 2402600, 'states_id' => 24, 'name' => 'Ceará-Mirim']);
		DB::table('cities')->insert(['id' => 2402709, 'states_id' => 24, 'name' => 'Cerro Corá']);
		DB::table('cities')->insert(['id' => 2402808, 'states_id' => 24, 'name' => 'Coronel Ezequiel']);
		DB::table('cities')->insert(['id' => 2402907, 'states_id' => 24, 'name' => 'Coronel João Pessoa']);
		DB::table('cities')->insert(['id' => 2403004, 'states_id' => 24, 'name' => 'Cruzeta']);
		DB::table('cities')->insert(['id' => 2403103, 'states_id' => 24, 'name' => 'Currais Novos']);
		DB::table('cities')->insert(['id' => 2403202, 'states_id' => 24, 'name' => 'Doutor Severiano']);
		DB::table('cities')->insert(['id' => 2403251, 'states_id' => 24, 'name' => 'Parnamirim']);
		DB::table('cities')->insert(['id' => 2403301, 'states_id' => 24, 'name' => 'Encanto']);
		DB::table('cities')->insert(['id' => 2403400, 'states_id' => 24, 'name' => 'Equador']);
		DB::table('cities')->insert(['id' => 2403509, 'states_id' => 24, 'name' => 'Espírito Santo']);
		DB::table('cities')->insert(['id' => 2403608, 'states_id' => 24, 'name' => 'Extremoz']);
		DB::table('cities')->insert(['id' => 2403707, 'states_id' => 24, 'name' => 'Felipe Guerra']);
		DB::table('cities')->insert(['id' => 2403756, 'states_id' => 24, 'name' => 'Fernando Pedroza']);
		DB::table('cities')->insert(['id' => 2403806, 'states_id' => 24, 'name' => 'Florânia']);
		DB::table('cities')->insert(['id' => 2403905, 'states_id' => 24, 'name' => 'Francisco Dantas']);
		DB::table('cities')->insert(['id' => 2404002, 'states_id' => 24, 'name' => 'Frutuoso Gomes']);
		DB::table('cities')->insert(['id' => 2404101, 'states_id' => 24, 'name' => 'Galinhos']);
		DB::table('cities')->insert(['id' => 2404200, 'states_id' => 24, 'name' => 'Goianinha']);
		DB::table('cities')->insert(['id' => 2404309, 'states_id' => 24, 'name' => 'Governador Dix-Sept Rosado']);
		DB::table('cities')->insert(['id' => 2404408, 'states_id' => 24, 'name' => 'Grossos']);
		DB::table('cities')->insert(['id' => 2404507, 'states_id' => 24, 'name' => 'Guamaré']);
		DB::table('cities')->insert(['id' => 2404606, 'states_id' => 24, 'name' => 'Ielmo Marinho']);
		DB::table('cities')->insert(['id' => 2404705, 'states_id' => 24, 'name' => 'Ipanguaçu']);
		DB::table('cities')->insert(['id' => 2404804, 'states_id' => 24, 'name' => 'Ipueira']);
		DB::table('cities')->insert(['id' => 2404853, 'states_id' => 24, 'name' => 'Itajá']);
		DB::table('cities')->insert(['id' => 2404903, 'states_id' => 24, 'name' => 'Itaú']);
		DB::table('cities')->insert(['id' => 2405009, 'states_id' => 24, 'name' => 'Jaçanã']);
		DB::table('cities')->insert(['id' => 2405108, 'states_id' => 24, 'name' => 'Jandaíra']);
		DB::table('cities')->insert(['id' => 2405207, 'states_id' => 24, 'name' => 'Janduís']);
		DB::table('cities')->insert(['id' => 2405306, 'states_id' => 24, 'name' => 'Januário Cicco']);
		DB::table('cities')->insert(['id' => 2405405, 'states_id' => 24, 'name' => 'Japi']);
		DB::table('cities')->insert(['id' => 2405504, 'states_id' => 24, 'name' => 'Jardim de Angicos']);
		DB::table('cities')->insert(['id' => 2405603, 'states_id' => 24, 'name' => 'Jardim de Piranhas']);
		DB::table('cities')->insert(['id' => 2405702, 'states_id' => 24, 'name' => 'Jardim do Seridó']);
		DB::table('cities')->insert(['id' => 2405801, 'states_id' => 24, 'name' => 'João Câmara']);
		DB::table('cities')->insert(['id' => 2405900, 'states_id' => 24, 'name' => 'João Dias']);
		DB::table('cities')->insert(['id' => 2406007, 'states_id' => 24, 'name' => 'José da Penha']);
		DB::table('cities')->insert(['id' => 2406106, 'states_id' => 24, 'name' => 'Jucurutu']);
		DB::table('cities')->insert(['id' => 2406155, 'states_id' => 24, 'name' => 'Jundiá']);
		DB::table('cities')->insert(['id' => 2406205, 'states_id' => 24, 'name' => 'Lagoa d\'Anta']);
		DB::table('cities')->insert(['id' => 2406304, 'states_id' => 24, 'name' => 'Lagoa de Pedras']);
		DB::table('cities')->insert(['id' => 2406403, 'states_id' => 24, 'name' => 'Lagoa de Velhos']);
		DB::table('cities')->insert(['id' => 2406502, 'states_id' => 24, 'name' => 'Lagoa Nova']);
		DB::table('cities')->insert(['id' => 2406601, 'states_id' => 24, 'name' => 'Lagoa Salgada']);
		DB::table('cities')->insert(['id' => 2406700, 'states_id' => 24, 'name' => 'Lajes']);
		DB::table('cities')->insert(['id' => 2406809, 'states_id' => 24, 'name' => 'Lajes Pintadas']);
		DB::table('cities')->insert(['id' => 2406908, 'states_id' => 24, 'name' => 'Lucrécia']);
		DB::table('cities')->insert(['id' => 2407005, 'states_id' => 24, 'name' => 'Luís Gomes']);
		DB::table('cities')->insert(['id' => 2407104, 'states_id' => 24, 'name' => 'Macaíba']);
		DB::table('cities')->insert(['id' => 2407203, 'states_id' => 24, 'name' => 'Macau']);
		DB::table('cities')->insert(['id' => 2407252, 'states_id' => 24, 'name' => 'Major Sales']);
		DB::table('cities')->insert(['id' => 2407302, 'states_id' => 24, 'name' => 'Marcelino Vieira']);
		DB::table('cities')->insert(['id' => 2407401, 'states_id' => 24, 'name' => 'Martins']);
		DB::table('cities')->insert(['id' => 2407500, 'states_id' => 24, 'name' => 'Maxaranguape']);
		DB::table('cities')->insert(['id' => 2407609, 'states_id' => 24, 'name' => 'Messias Targino']);
		DB::table('cities')->insert(['id' => 2407708, 'states_id' => 24, 'name' => 'Montanhas']);
		DB::table('cities')->insert(['id' => 2407807, 'states_id' => 24, 'name' => 'Monte Alegre']);
		DB::table('cities')->insert(['id' => 2407906, 'states_id' => 24, 'name' => 'Monte das Gameleiras']);
		DB::table('cities')->insert(['id' => 2408003, 'states_id' => 24, 'name' => 'Mossoró']);
		DB::table('cities')->insert(['id' => 2408102, 'states_id' => 24, 'name' => 'Natal']);
		DB::table('cities')->insert(['id' => 2408201, 'states_id' => 24, 'name' => 'Nísia Floresta']);
		DB::table('cities')->insert(['id' => 2408300, 'states_id' => 24, 'name' => 'Nova Cruz']);
		DB::table('cities')->insert(['id' => 2408409, 'states_id' => 24, 'name' => 'Olho-d\'Água do Borges']);
		DB::table('cities')->insert(['id' => 2408508, 'states_id' => 24, 'name' => 'Ouro Branco']);
		DB::table('cities')->insert(['id' => 2408607, 'states_id' => 24, 'name' => 'Paraná']);
		DB::table('cities')->insert(['id' => 2408706, 'states_id' => 24, 'name' => 'Paraú']);
		DB::table('cities')->insert(['id' => 2408805, 'states_id' => 24, 'name' => 'Parazinho']);
		DB::table('cities')->insert(['id' => 2408904, 'states_id' => 24, 'name' => 'Parelhas']);
		DB::table('cities')->insert(['id' => 2408953, 'states_id' => 24, 'name' => 'Rio do Fogo']);
		DB::table('cities')->insert(['id' => 2409100, 'states_id' => 24, 'name' => 'Passa e Fica']);
		DB::table('cities')->insert(['id' => 2409209, 'states_id' => 24, 'name' => 'Passagem']);
		DB::table('cities')->insert(['id' => 2409308, 'states_id' => 24, 'name' => 'Patu']);
		DB::table('cities')->insert(['id' => 2409332, 'states_id' => 24, 'name' => 'Santa Maria']);
		DB::table('cities')->insert(['id' => 2409407, 'states_id' => 24, 'name' => 'Pau dos Ferros']);
		DB::table('cities')->insert(['id' => 2409506, 'states_id' => 24, 'name' => 'Pedra Grande']);
		DB::table('cities')->insert(['id' => 2409605, 'states_id' => 24, 'name' => 'Pedra Preta']);
		DB::table('cities')->insert(['id' => 2409704, 'states_id' => 24, 'name' => 'Pedro Avelino']);
		DB::table('cities')->insert(['id' => 2409803, 'states_id' => 24, 'name' => 'Pedro Velho']);
		DB::table('cities')->insert(['id' => 2409902, 'states_id' => 24, 'name' => 'Pendências']);
		DB::table('cities')->insert(['id' => 2410009, 'states_id' => 24, 'name' => 'Pilões']);
		DB::table('cities')->insert(['id' => 2410108, 'states_id' => 24, 'name' => 'Poço Branco']);
		DB::table('cities')->insert(['id' => 2410207, 'states_id' => 24, 'name' => 'Portalegre']);
		DB::table('cities')->insert(['id' => 2410256, 'states_id' => 24, 'name' => 'Porto do Mangue']);
		DB::table('cities')->insert(['id' => 2410306, 'states_id' => 24, 'name' => 'Presidente Juscelino']);
		DB::table('cities')->insert(['id' => 2410405, 'states_id' => 24, 'name' => 'Pureza']);
		DB::table('cities')->insert(['id' => 2410504, 'states_id' => 24, 'name' => 'Rafael Fernandes']);
		DB::table('cities')->insert(['id' => 2410603, 'states_id' => 24, 'name' => 'Rafael Godeiro']);
		DB::table('cities')->insert(['id' => 2410702, 'states_id' => 24, 'name' => 'Riacho da Cruz']);
		DB::table('cities')->insert(['id' => 2410801, 'states_id' => 24, 'name' => 'Riacho de Santana']);
		DB::table('cities')->insert(['id' => 2410900, 'states_id' => 24, 'name' => 'Riachuelo']);
		DB::table('cities')->insert(['id' => 2411007, 'states_id' => 24, 'name' => 'Rodolfo Fernandes']);
		DB::table('cities')->insert(['id' => 2411056, 'states_id' => 24, 'name' => 'Tibau']);
		DB::table('cities')->insert(['id' => 2411106, 'states_id' => 24, 'name' => 'Ruy Barbosa']);
		DB::table('cities')->insert(['id' => 2411205, 'states_id' => 24, 'name' => 'Santa Cruz']);
		DB::table('cities')->insert(['id' => 2411403, 'states_id' => 24, 'name' => 'Santana do Matos']);
		DB::table('cities')->insert(['id' => 2411429, 'states_id' => 24, 'name' => 'Santana do Seridó']);
		DB::table('cities')->insert(['id' => 2411502, 'states_id' => 24, 'name' => 'Santo Antônio']);
		DB::table('cities')->insert(['id' => 2411601, 'states_id' => 24, 'name' => 'São Bento do Norte']);
		DB::table('cities')->insert(['id' => 2411700, 'states_id' => 24, 'name' => 'São Bento do Trairí']);
		DB::table('cities')->insert(['id' => 2411809, 'states_id' => 24, 'name' => 'São Fernando']);
		DB::table('cities')->insert(['id' => 2411908, 'states_id' => 24, 'name' => 'São Francisco do Oeste']);
		DB::table('cities')->insert(['id' => 2412005, 'states_id' => 24, 'name' => 'São Gonçalo do Amarante']);
		DB::table('cities')->insert(['id' => 2412104, 'states_id' => 24, 'name' => 'São João do Sabugi']);
		DB::table('cities')->insert(['id' => 2412203, 'states_id' => 24, 'name' => 'São José de Mipibu']);
		DB::table('cities')->insert(['id' => 2412302, 'states_id' => 24, 'name' => 'São José do Campestre']);
		DB::table('cities')->insert(['id' => 2412401, 'states_id' => 24, 'name' => 'São José do Seridó']);
		DB::table('cities')->insert(['id' => 2412500, 'states_id' => 24, 'name' => 'São Miguel']);
		DB::table('cities')->insert(['id' => 2412559, 'states_id' => 24, 'name' => 'São Miguel do Gostoso']);
		DB::table('cities')->insert(['id' => 2412609, 'states_id' => 24, 'name' => 'São Paulo do Potengi']);
		DB::table('cities')->insert(['id' => 2412708, 'states_id' => 24, 'name' => 'São Pedro']);
		DB::table('cities')->insert(['id' => 2412807, 'states_id' => 24, 'name' => 'São Rafael']);
		DB::table('cities')->insert(['id' => 2412906, 'states_id' => 24, 'name' => 'São Tomé']);
		DB::table('cities')->insert(['id' => 2413003, 'states_id' => 24, 'name' => 'São Vicente']);
		DB::table('cities')->insert(['id' => 2413102, 'states_id' => 24, 'name' => 'Senador Elói de Souza']);
		DB::table('cities')->insert(['id' => 2413201, 'states_id' => 24, 'name' => 'Senador Georgino Avelino']);
		DB::table('cities')->insert(['id' => 2413300, 'states_id' => 24, 'name' => 'Serra de São Bento']);
		DB::table('cities')->insert(['id' => 2413359, 'states_id' => 24, 'name' => 'Serra do Mel']);
		DB::table('cities')->insert(['id' => 2413409, 'states_id' => 24, 'name' => 'Serra Negra do Norte']);
		DB::table('cities')->insert(['id' => 2413508, 'states_id' => 24, 'name' => 'Serrinha']);
		DB::table('cities')->insert(['id' => 2413557, 'states_id' => 24, 'name' => 'Serrinha dos Pintos']);
		DB::table('cities')->insert(['id' => 2413607, 'states_id' => 24, 'name' => 'Severiano Melo']);
		DB::table('cities')->insert(['id' => 2413706, 'states_id' => 24, 'name' => 'Sítio Novo']);
		DB::table('cities')->insert(['id' => 2413805, 'states_id' => 24, 'name' => 'Taboleiro Grande']);
		DB::table('cities')->insert(['id' => 2413904, 'states_id' => 24, 'name' => 'Taipu']);
		DB::table('cities')->insert(['id' => 2414001, 'states_id' => 24, 'name' => 'Tangará']);
		DB::table('cities')->insert(['id' => 2414100, 'states_id' => 24, 'name' => 'Tenente Ananias']);
		DB::table('cities')->insert(['id' => 2414159, 'states_id' => 24, 'name' => 'Tenente Laurentino Cruz']);
		DB::table('cities')->insert(['id' => 2414209, 'states_id' => 24, 'name' => 'Tibau do Sul']);
		DB::table('cities')->insert(['id' => 2414308, 'states_id' => 24, 'name' => 'Timbaúba dos Batistas']);
		DB::table('cities')->insert(['id' => 2414407, 'states_id' => 24, 'name' => 'Touros']);
		DB::table('cities')->insert(['id' => 2414456, 'states_id' => 24, 'name' => 'Triunfo Potiguar']);
		DB::table('cities')->insert(['id' => 2414506, 'states_id' => 24, 'name' => 'Umarizal']);
		DB::table('cities')->insert(['id' => 2414605, 'states_id' => 24, 'name' => 'Upanema']);
		DB::table('cities')->insert(['id' => 2414704, 'states_id' => 24, 'name' => 'Várzea']);
		DB::table('cities')->insert(['id' => 2414753, 'states_id' => 24, 'name' => 'Venha-Ver']);
		DB::table('cities')->insert(['id' => 2414803, 'states_id' => 24, 'name' => 'Vera Cruz']);
		DB::table('cities')->insert(['id' => 2414902, 'states_id' => 24, 'name' => 'Viçosa']);
		DB::table('cities')->insert(['id' => 2415008, 'states_id' => 24, 'name' => 'Vila Flor']);
    }
}
