<?php

use Illuminate\Database\Seeder;

class CitiesTablePRSeeder extends Seeder
{
    /**
     * Alimenta um schema de cities com as cities do Paraná
     * @author Cesar André (https://github.com/cesar-andre)
     * @return void
     */
    public function run()
    {
    	DB::table('cities')->insert(['id' => 4100103, 'states_id' => 41, 'name' => 'Abatiá']);
		DB::table('cities')->insert(['id' => 4100202, 'states_id' => 41, 'name' => 'Adrianópolis']);
		DB::table('cities')->insert(['id' => 4100301, 'states_id' => 41, 'name' => 'Agudos do Sul']);
		DB::table('cities')->insert(['id' => 4100400, 'states_id' => 41, 'name' => 'Almirante Tamandaré']);
		DB::table('cities')->insert(['id' => 4100459, 'states_id' => 41, 'name' => 'Altamira do Paraná']);
		DB::table('cities')->insert(['id' => 4100509, 'states_id' => 41, 'name' => 'Altônia']);
		DB::table('cities')->insert(['id' => 4100608, 'states_id' => 41, 'name' => 'Alto Paraná']);
		DB::table('cities')->insert(['id' => 4100707, 'states_id' => 41, 'name' => 'Alto Piquiri']);
		DB::table('cities')->insert(['id' => 4100806, 'states_id' => 41, 'name' => 'Alvorada do Sul']);
		DB::table('cities')->insert(['id' => 4100905, 'states_id' => 41, 'name' => 'Amaporã']);
		DB::table('cities')->insert(['id' => 4101002, 'states_id' => 41, 'name' => 'Ampére']);
		DB::table('cities')->insert(['id' => 4101051, 'states_id' => 41, 'name' => 'Anahy']);
		DB::table('cities')->insert(['id' => 4101101, 'states_id' => 41, 'name' => 'Andirá']);
		DB::table('cities')->insert(['id' => 4101150, 'states_id' => 41, 'name' => 'Ângulo']);
		DB::table('cities')->insert(['id' => 4101200, 'states_id' => 41, 'name' => 'Antonina']);
		DB::table('cities')->insert(['id' => 4101309, 'states_id' => 41, 'name' => 'Antônio Olinto']);
		DB::table('cities')->insert(['id' => 4101408, 'states_id' => 41, 'name' => 'Apucarana']);
		DB::table('cities')->insert(['id' => 4101507, 'states_id' => 41, 'name' => 'Arapongas']);
		DB::table('cities')->insert(['id' => 4101606, 'states_id' => 41, 'name' => 'Arapoti']);
		DB::table('cities')->insert(['id' => 4101655, 'states_id' => 41, 'name' => 'Arapuã']);
		DB::table('cities')->insert(['id' => 4101705, 'states_id' => 41, 'name' => 'Araruna']);
		DB::table('cities')->insert(['id' => 4101804, 'states_id' => 41, 'name' => 'Araucária']);
		DB::table('cities')->insert(['id' => 4101853, 'states_id' => 41, 'name' => 'Ariranha do Ivaí']);
		DB::table('cities')->insert(['id' => 4101903, 'states_id' => 41, 'name' => 'Assaí']);
		DB::table('cities')->insert(['id' => 4102000, 'states_id' => 41, 'name' => 'Assis Chateaubriand']);
		DB::table('cities')->insert(['id' => 4102109, 'states_id' => 41, 'name' => 'Astorga']);
		DB::table('cities')->insert(['id' => 4102208, 'states_id' => 41, 'name' => 'Atalaia']);
		DB::table('cities')->insert(['id' => 4102307, 'states_id' => 41, 'name' => 'Balsa Nova']);
		DB::table('cities')->insert(['id' => 4102406, 'states_id' => 41, 'name' => 'Bandeirantes']);
		DB::table('cities')->insert(['id' => 4102505, 'states_id' => 41, 'name' => 'Barbosa Ferraz']);
		DB::table('cities')->insert(['id' => 4102604, 'states_id' => 41, 'name' => 'Barracão']);
		DB::table('cities')->insert(['id' => 4102703, 'states_id' => 41, 'name' => 'Barra do Jacaré']);
		DB::table('cities')->insert(['id' => 4102752, 'states_id' => 41, 'name' => 'Bela Vista da Caroba']);
		DB::table('cities')->insert(['id' => 4102802, 'states_id' => 41, 'name' => 'Bela Vista do Paraíso']);
		DB::table('cities')->insert(['id' => 4102901, 'states_id' => 41, 'name' => 'Bituruna']);
		DB::table('cities')->insert(['id' => 4103008, 'states_id' => 41, 'name' => 'Boa Esperança']);
		DB::table('cities')->insert(['id' => 4103024, 'states_id' => 41, 'name' => 'Boa Esperança do Iguaçu']);
		DB::table('cities')->insert(['id' => 4103040, 'states_id' => 41, 'name' => 'Boa Ventura de São Roque']);
		DB::table('cities')->insert(['id' => 4103057, 'states_id' => 41, 'name' => 'Boa Vista da Aparecida']);
		DB::table('cities')->insert(['id' => 4103107, 'states_id' => 41, 'name' => 'Bocaiúva do Sul']);
		DB::table('cities')->insert(['id' => 4103156, 'states_id' => 41, 'name' => 'Bom Jesus do Sul']);
		DB::table('cities')->insert(['id' => 4103206, 'states_id' => 41, 'name' => 'Bom Sucesso']);
		DB::table('cities')->insert(['id' => 4103222, 'states_id' => 41, 'name' => 'Bom Sucesso do Sul']);
		DB::table('cities')->insert(['id' => 4103305, 'states_id' => 41, 'name' => 'Borrazópolis']);
		DB::table('cities')->insert(['id' => 4103354, 'states_id' => 41, 'name' => 'Braganey']);
		DB::table('cities')->insert(['id' => 4103370, 'states_id' => 41, 'name' => 'Brasilândia do Sul']);
		DB::table('cities')->insert(['id' => 4103404, 'states_id' => 41, 'name' => 'Cafeara']);
		DB::table('cities')->insert(['id' => 4103453, 'states_id' => 41, 'name' => 'Cafelândia']);
		DB::table('cities')->insert(['id' => 4103479, 'states_id' => 41, 'name' => 'Cafezal do Sul']);
		DB::table('cities')->insert(['id' => 4103503, 'states_id' => 41, 'name' => 'Califórnia']);
		DB::table('cities')->insert(['id' => 4103602, 'states_id' => 41, 'name' => 'Cambará']);
		DB::table('cities')->insert(['id' => 4103701, 'states_id' => 41, 'name' => 'Cambé']);
		DB::table('cities')->insert(['id' => 4103800, 'states_id' => 41, 'name' => 'Cambira']);
		DB::table('cities')->insert(['id' => 4103909, 'states_id' => 41, 'name' => 'Campina da Lagoa']);
		DB::table('cities')->insert(['id' => 4103958, 'states_id' => 41, 'name' => 'Campina do Simão']);
		DB::table('cities')->insert(['id' => 4104006, 'states_id' => 41, 'name' => 'Campina Grande do Sul']);
		DB::table('cities')->insert(['id' => 4104055, 'states_id' => 41, 'name' => 'Campo Bonito']);
		DB::table('cities')->insert(['id' => 4104105, 'states_id' => 41, 'name' => 'Campo do Tenente']);
		DB::table('cities')->insert(['id' => 4104204, 'states_id' => 41, 'name' => 'Campo Largo']);
		DB::table('cities')->insert(['id' => 4104253, 'states_id' => 41, 'name' => 'Campo Magro']);
		DB::table('cities')->insert(['id' => 4104303, 'states_id' => 41, 'name' => 'Campo Mourão']);
		DB::table('cities')->insert(['id' => 4104402, 'states_id' => 41, 'name' => 'Cândido de Abreu']);
		DB::table('cities')->insert(['id' => 4104428, 'states_id' => 41, 'name' => 'Candói']);
		DB::table('cities')->insert(['id' => 4104451, 'states_id' => 41, 'name' => 'Cantagalo']);
		DB::table('cities')->insert(['id' => 4104501, 'states_id' => 41, 'name' => 'Capanema']);
		DB::table('cities')->insert(['id' => 4104600, 'states_id' => 41, 'name' => 'Capitão Leônidas Marques']);
		DB::table('cities')->insert(['id' => 4104659, 'states_id' => 41, 'name' => 'Carambeí']);
		DB::table('cities')->insert(['id' => 4104709, 'states_id' => 41, 'name' => 'Carlópolis']);
		DB::table('cities')->insert(['id' => 4104808, 'states_id' => 41, 'name' => 'Cascavel']);
		DB::table('cities')->insert(['id' => 4104907, 'states_id' => 41, 'name' => 'Castro']);
		DB::table('cities')->insert(['id' => 4105003, 'states_id' => 41, 'name' => 'Catanduvas']);
		DB::table('cities')->insert(['id' => 4105102, 'states_id' => 41, 'name' => 'Centenário do Sul']);
		DB::table('cities')->insert(['id' => 4105201, 'states_id' => 41, 'name' => 'Cerro Azul']);
		DB::table('cities')->insert(['id' => 4105300, 'states_id' => 41, 'name' => 'Céu Azul']);
		DB::table('cities')->insert(['id' => 4105409, 'states_id' => 41, 'name' => 'Chopinzinho']);
		DB::table('cities')->insert(['id' => 4105508, 'states_id' => 41, 'name' => 'Cianorte']);
		DB::table('cities')->insert(['id' => 4105607, 'states_id' => 41, 'name' => 'Cidade Gaúcha']);
		DB::table('cities')->insert(['id' => 4105706, 'states_id' => 41, 'name' => 'Clevelândia']);
		DB::table('cities')->insert(['id' => 4105805, 'states_id' => 41, 'name' => 'Colombo']);
		DB::table('cities')->insert(['id' => 4105904, 'states_id' => 41, 'name' => 'Colorado']);
		DB::table('cities')->insert(['id' => 4106001, 'states_id' => 41, 'name' => 'Congonhinhas']);
		DB::table('cities')->insert(['id' => 4106100, 'states_id' => 41, 'name' => 'Conselheiro Mairinck']);
		DB::table('cities')->insert(['id' => 4106209, 'states_id' => 41, 'name' => 'Contenda']);
		DB::table('cities')->insert(['id' => 4106308, 'states_id' => 41, 'name' => 'Corbélia']);
		DB::table('cities')->insert(['id' => 4106407, 'states_id' => 41, 'name' => 'Cornélio Procópio']);
		DB::table('cities')->insert(['id' => 4106456, 'states_id' => 41, 'name' => 'Coronel Domingos Soares']);
		DB::table('cities')->insert(['id' => 4106506, 'states_id' => 41, 'name' => 'Coronel Vivida']);
		DB::table('cities')->insert(['id' => 4106555, 'states_id' => 41, 'name' => 'Corumbataí do Sul']);
		DB::table('cities')->insert(['id' => 4106571, 'states_id' => 41, 'name' => 'Cruzeiro do Iguaçu']);
		DB::table('cities')->insert(['id' => 4106605, 'states_id' => 41, 'name' => 'Cruzeiro do Oeste']);
		DB::table('cities')->insert(['id' => 4106704, 'states_id' => 41, 'name' => 'Cruzeiro do Sul']);
		DB::table('cities')->insert(['id' => 4106803, 'states_id' => 41, 'name' => 'Cruz Machado']);
		DB::table('cities')->insert(['id' => 4106852, 'states_id' => 41, 'name' => 'Cruzmaltina']);
		DB::table('cities')->insert(['id' => 4106902, 'states_id' => 41, 'name' => 'Curitiba']);
		DB::table('cities')->insert(['id' => 4107009, 'states_id' => 41, 'name' => 'Curiúva']);
		DB::table('cities')->insert(['id' => 4107108, 'states_id' => 41, 'name' => 'Diamante do Norte']);
		DB::table('cities')->insert(['id' => 4107124, 'states_id' => 41, 'name' => 'Diamante do Sul']);
		DB::table('cities')->insert(['id' => 4107157, 'states_id' => 41, 'name' => 'Diamante D\'Oeste']);
		DB::table('cities')->insert(['id' => 4107207, 'states_id' => 41, 'name' => 'Dois Vizinhos']);
		DB::table('cities')->insert(['id' => 4107256, 'states_id' => 41, 'name' => 'Douradina']);
		DB::table('cities')->insert(['id' => 4107306, 'states_id' => 41, 'name' => 'Doutor Camargo']);
		DB::table('cities')->insert(['id' => 4107405, 'states_id' => 41, 'name' => 'Enéas Marques']);
		DB::table('cities')->insert(['id' => 4107504, 'states_id' => 41, 'name' => 'Engenheiro Beltrão']);
		DB::table('cities')->insert(['id' => 4107520, 'states_id' => 41, 'name' => 'Esperança Nova']);
		DB::table('cities')->insert(['id' => 4107538, 'states_id' => 41, 'name' => 'Entre Rios do Oeste']);
		DB::table('cities')->insert(['id' => 4107546, 'states_id' => 41, 'name' => 'Espigão Alto do Iguaçu']);
		DB::table('cities')->insert(['id' => 4107553, 'states_id' => 41, 'name' => 'Farol']);
		DB::table('cities')->insert(['id' => 4107603, 'states_id' => 41, 'name' => 'Faxinal']);
		DB::table('cities')->insert(['id' => 4107652, 'states_id' => 41, 'name' => 'Fazenda Rio Grande']);
		DB::table('cities')->insert(['id' => 4107702, 'states_id' => 41, 'name' => 'Fênix']);
		DB::table('cities')->insert(['id' => 4107736, 'states_id' => 41, 'name' => 'Fernandes Pinheiro']);
		DB::table('cities')->insert(['id' => 4107751, 'states_id' => 41, 'name' => 'Figueira']);
		DB::table('cities')->insert(['id' => 4107801, 'states_id' => 41, 'name' => 'Floraí']);
		DB::table('cities')->insert(['id' => 4107850, 'states_id' => 41, 'name' => 'Flor da Serra do Sul']);
		DB::table('cities')->insert(['id' => 4107900, 'states_id' => 41, 'name' => 'Floresta']);
		DB::table('cities')->insert(['id' => 4108007, 'states_id' => 41, 'name' => 'Florestópolis']);
		DB::table('cities')->insert(['id' => 4108106, 'states_id' => 41, 'name' => 'Flórida']);
		DB::table('cities')->insert(['id' => 4108205, 'states_id' => 41, 'name' => 'Formosa do Oeste']);
		DB::table('cities')->insert(['id' => 4108304, 'states_id' => 41, 'name' => 'Foz do Iguaçu']);
		DB::table('cities')->insert(['id' => 4108320, 'states_id' => 41, 'name' => 'Francisco Alves']);
		DB::table('cities')->insert(['id' => 4108403, 'states_id' => 41, 'name' => 'Francisco Beltrão']);
		DB::table('cities')->insert(['id' => 4108452, 'states_id' => 41, 'name' => 'Foz do Jordão']);
		DB::table('cities')->insert(['id' => 4108502, 'states_id' => 41, 'name' => 'General Carneiro']);
		DB::table('cities')->insert(['id' => 4108551, 'states_id' => 41, 'name' => 'Godoy Moreira']);
		DB::table('cities')->insert(['id' => 4108601, 'states_id' => 41, 'name' => 'Goioerê']);
		DB::table('cities')->insert(['id' => 4108650, 'states_id' => 41, 'name' => 'Goioxim']);
		DB::table('cities')->insert(['id' => 4108700, 'states_id' => 41, 'name' => 'Grandes Rios']);
		DB::table('cities')->insert(['id' => 4108809, 'states_id' => 41, 'name' => 'Guaíra']);
		DB::table('cities')->insert(['id' => 4108908, 'states_id' => 41, 'name' => 'Guairaçá']);
		DB::table('cities')->insert(['id' => 4108957, 'states_id' => 41, 'name' => 'Guamiranga']);
		DB::table('cities')->insert(['id' => 4109005, 'states_id' => 41, 'name' => 'Guapirama']);
		DB::table('cities')->insert(['id' => 4109104, 'states_id' => 41, 'name' => 'Guaporema']);
		DB::table('cities')->insert(['id' => 4109203, 'states_id' => 41, 'name' => 'Guaraci']);
		DB::table('cities')->insert(['id' => 4109302, 'states_id' => 41, 'name' => 'Guaraniaçu']);
		DB::table('cities')->insert(['id' => 4109401, 'states_id' => 41, 'name' => 'Guarapuava']);
		DB::table('cities')->insert(['id' => 4109500, 'states_id' => 41, 'name' => 'Guaraqueçaba']);
		DB::table('cities')->insert(['id' => 4109609, 'states_id' => 41, 'name' => 'Guaratuba']);
		DB::table('cities')->insert(['id' => 4109658, 'states_id' => 41, 'name' => 'Honório Serpa']);
		DB::table('cities')->insert(['id' => 4109708, 'states_id' => 41, 'name' => 'Ibaiti']);
		DB::table('cities')->insert(['id' => 4109757, 'states_id' => 41, 'name' => 'Ibema']);
		DB::table('cities')->insert(['id' => 4109807, 'states_id' => 41, 'name' => 'Ibiporã']);
		DB::table('cities')->insert(['id' => 4109906, 'states_id' => 41, 'name' => 'Icaraíma']);
		DB::table('cities')->insert(['id' => 4110003, 'states_id' => 41, 'name' => 'Iguaraçu']);
		DB::table('cities')->insert(['id' => 4110052, 'states_id' => 41, 'name' => 'Iguatu']);
		DB::table('cities')->insert(['id' => 4110078, 'states_id' => 41, 'name' => 'Imbaú']);
		DB::table('cities')->insert(['id' => 4110102, 'states_id' => 41, 'name' => 'Imbituva']);
		DB::table('cities')->insert(['id' => 4110201, 'states_id' => 41, 'name' => 'Inácio Martins']);
		DB::table('cities')->insert(['id' => 4110300, 'states_id' => 41, 'name' => 'Inajá']);
		DB::table('cities')->insert(['id' => 4110409, 'states_id' => 41, 'name' => 'Indianópolis']);
		DB::table('cities')->insert(['id' => 4110508, 'states_id' => 41, 'name' => 'Ipiranga']);
		DB::table('cities')->insert(['id' => 4110607, 'states_id' => 41, 'name' => 'Iporã']);
		DB::table('cities')->insert(['id' => 4110656, 'states_id' => 41, 'name' => 'Iracema do Oeste']);
		DB::table('cities')->insert(['id' => 4110706, 'states_id' => 41, 'name' => 'Irati']);
		DB::table('cities')->insert(['id' => 4110805, 'states_id' => 41, 'name' => 'Iretama']);
		DB::table('cities')->insert(['id' => 4110904, 'states_id' => 41, 'name' => 'Itaguajé']);
		DB::table('cities')->insert(['id' => 4110953, 'states_id' => 41, 'name' => 'Itaipulândia']);
		DB::table('cities')->insert(['id' => 4111001, 'states_id' => 41, 'name' => 'Itambaracá']);
		DB::table('cities')->insert(['id' => 4111100, 'states_id' => 41, 'name' => 'Itambé']);
		DB::table('cities')->insert(['id' => 4111209, 'states_id' => 41, 'name' => 'Itapejara d\'Oeste']);
		DB::table('cities')->insert(['id' => 4111258, 'states_id' => 41, 'name' => 'Itaperuçu']);
		DB::table('cities')->insert(['id' => 4111308, 'states_id' => 41, 'name' => 'Itaúna do Sul']);
		DB::table('cities')->insert(['id' => 4111407, 'states_id' => 41, 'name' => 'Ivaí']);
		DB::table('cities')->insert(['id' => 4111506, 'states_id' => 41, 'name' => 'Ivaiporã']);
		DB::table('cities')->insert(['id' => 4111555, 'states_id' => 41, 'name' => 'Ivaté']);
		DB::table('cities')->insert(['id' => 4111605, 'states_id' => 41, 'name' => 'Ivatuba']);
		DB::table('cities')->insert(['id' => 4111704, 'states_id' => 41, 'name' => 'Jaboti']);
		DB::table('cities')->insert(['id' => 4111803, 'states_id' => 41, 'name' => 'Jacarezinho']);
		DB::table('cities')->insert(['id' => 4111902, 'states_id' => 41, 'name' => 'Jaguapitã']);
		DB::table('cities')->insert(['id' => 4112009, 'states_id' => 41, 'name' => 'Jaguariaíva']);
		DB::table('cities')->insert(['id' => 4112108, 'states_id' => 41, 'name' => 'Jandaia do Sul']);
		DB::table('cities')->insert(['id' => 4112207, 'states_id' => 41, 'name' => 'Janiópolis']);
		DB::table('cities')->insert(['id' => 4112306, 'states_id' => 41, 'name' => 'Japira']);
		DB::table('cities')->insert(['id' => 4112405, 'states_id' => 41, 'name' => 'Japurá']);
		DB::table('cities')->insert(['id' => 4112504, 'states_id' => 41, 'name' => 'Jardim Alegre']);
		DB::table('cities')->insert(['id' => 4112603, 'states_id' => 41, 'name' => 'Jardim Olinda']);
		DB::table('cities')->insert(['id' => 4112702, 'states_id' => 41, 'name' => 'Jataizinho']);
		DB::table('cities')->insert(['id' => 4112751, 'states_id' => 41, 'name' => 'Jesuítas']);
		DB::table('cities')->insert(['id' => 4112801, 'states_id' => 41, 'name' => 'Joaquim Távora']);
		DB::table('cities')->insert(['id' => 4112900, 'states_id' => 41, 'name' => 'Jundiaí do Sul']);
		DB::table('cities')->insert(['id' => 4112959, 'states_id' => 41, 'name' => 'Juranda']);
		DB::table('cities')->insert(['id' => 4113007, 'states_id' => 41, 'name' => 'Jussara']);
		DB::table('cities')->insert(['id' => 4113106, 'states_id' => 41, 'name' => 'Kaloré']);
		DB::table('cities')->insert(['id' => 4113205, 'states_id' => 41, 'name' => 'Lapa']);
		DB::table('cities')->insert(['id' => 4113254, 'states_id' => 41, 'name' => 'Laranjal']);
		DB::table('cities')->insert(['id' => 4113304, 'states_id' => 41, 'name' => 'Laranjeiras do Sul']);
		DB::table('cities')->insert(['id' => 4113403, 'states_id' => 41, 'name' => 'Leópolis']);
		DB::table('cities')->insert(['id' => 4113429, 'states_id' => 41, 'name' => 'Lidianópolis']);
		DB::table('cities')->insert(['id' => 4113452, 'states_id' => 41, 'name' => 'Lindoeste']);
		DB::table('cities')->insert(['id' => 4113502, 'states_id' => 41, 'name' => 'Loanda']);
		DB::table('cities')->insert(['id' => 4113601, 'states_id' => 41, 'name' => 'Lobato']);
		DB::table('cities')->insert(['id' => 4113700, 'states_id' => 41, 'name' => 'Londrina']);
		DB::table('cities')->insert(['id' => 4113734, 'states_id' => 41, 'name' => 'Luiziana']);
		DB::table('cities')->insert(['id' => 4113759, 'states_id' => 41, 'name' => 'Lunardelli']);
		DB::table('cities')->insert(['id' => 4113809, 'states_id' => 41, 'name' => 'Lupionópolis']);
		DB::table('cities')->insert(['id' => 4113908, 'states_id' => 41, 'name' => 'Mallet']);
		DB::table('cities')->insert(['id' => 4114005, 'states_id' => 41, 'name' => 'Mamborê']);
		DB::table('cities')->insert(['id' => 4114104, 'states_id' => 41, 'name' => 'Mandaguaçu']);
		DB::table('cities')->insert(['id' => 4114203, 'states_id' => 41, 'name' => 'Mandaguari']);
		DB::table('cities')->insert(['id' => 4114302, 'states_id' => 41, 'name' => 'Mandirituba']);
		DB::table('cities')->insert(['id' => 4114351, 'states_id' => 41, 'name' => 'Manfrinópolis']);
		DB::table('cities')->insert(['id' => 4114401, 'states_id' => 41, 'name' => 'Mangueirinha']);
		DB::table('cities')->insert(['id' => 4114500, 'states_id' => 41, 'name' => 'Manoel Ribas']);
		DB::table('cities')->insert(['id' => 4114609, 'states_id' => 41, 'name' => 'Marechal Cândido Rondon']);
		DB::table('cities')->insert(['id' => 4114708, 'states_id' => 41, 'name' => 'Maria Helena']);
		DB::table('cities')->insert(['id' => 4114807, 'states_id' => 41, 'name' => 'Marialva']);
		DB::table('cities')->insert(['id' => 4114906, 'states_id' => 41, 'name' => 'Marilândia do Sul']);
		DB::table('cities')->insert(['id' => 4115002, 'states_id' => 41, 'name' => 'Marilena']);
		DB::table('cities')->insert(['id' => 4115101, 'states_id' => 41, 'name' => 'Mariluz']);
		DB::table('cities')->insert(['id' => 4115200, 'states_id' => 41, 'name' => 'Maringá']);
		DB::table('cities')->insert(['id' => 4115309, 'states_id' => 41, 'name' => 'Mariópolis']);
		DB::table('cities')->insert(['id' => 4115358, 'states_id' => 41, 'name' => 'Maripá']);
		DB::table('cities')->insert(['id' => 4115408, 'states_id' => 41, 'name' => 'Marmeleiro']);
		DB::table('cities')->insert(['id' => 4115457, 'states_id' => 41, 'name' => 'Marquinho']);
		DB::table('cities')->insert(['id' => 4115507, 'states_id' => 41, 'name' => 'Marumbi']);
		DB::table('cities')->insert(['id' => 4115606, 'states_id' => 41, 'name' => 'Matelândia']);
		DB::table('cities')->insert(['id' => 4115705, 'states_id' => 41, 'name' => 'Matinhos']);
		DB::table('cities')->insert(['id' => 4115739, 'states_id' => 41, 'name' => 'Mato Rico']);
		DB::table('cities')->insert(['id' => 4115754, 'states_id' => 41, 'name' => 'Mauá da Serra']);
		DB::table('cities')->insert(['id' => 4115804, 'states_id' => 41, 'name' => 'Medianeira']);
		DB::table('cities')->insert(['id' => 4115853, 'states_id' => 41, 'name' => 'Mercedes']);
		DB::table('cities')->insert(['id' => 4115903, 'states_id' => 41, 'name' => 'Mirador']);
		DB::table('cities')->insert(['id' => 4116000, 'states_id' => 41, 'name' => 'Miraselva']);
		DB::table('cities')->insert(['id' => 4116059, 'states_id' => 41, 'name' => 'Missal']);
		DB::table('cities')->insert(['id' => 4116109, 'states_id' => 41, 'name' => 'Moreira Sales']);
		DB::table('cities')->insert(['id' => 4116208, 'states_id' => 41, 'name' => 'Morretes']);
		DB::table('cities')->insert(['id' => 4116307, 'states_id' => 41, 'name' => 'Munhoz de Melo']);
		DB::table('cities')->insert(['id' => 4116406, 'states_id' => 41, 'name' => 'Nossa Senhora das Graças']);
		DB::table('cities')->insert(['id' => 4116505, 'states_id' => 41, 'name' => 'Nova Aliança do Ivaí']);
		DB::table('cities')->insert(['id' => 4116604, 'states_id' => 41, 'name' => 'Nova América da Colina']);
		DB::table('cities')->insert(['id' => 4116703, 'states_id' => 41, 'name' => 'Nova Aurora']);
		DB::table('cities')->insert(['id' => 4116802, 'states_id' => 41, 'name' => 'Nova Cantu']);
		DB::table('cities')->insert(['id' => 4116901, 'states_id' => 41, 'name' => 'Nova Esperança']);
		DB::table('cities')->insert(['id' => 4116950, 'states_id' => 41, 'name' => 'Nova Esperança do Sudoeste']);
		DB::table('cities')->insert(['id' => 4117008, 'states_id' => 41, 'name' => 'Nova Fátima']);
		DB::table('cities')->insert(['id' => 4117057, 'states_id' => 41, 'name' => 'Nova Laranjeiras']);
		DB::table('cities')->insert(['id' => 4117107, 'states_id' => 41, 'name' => 'Nova Londrina']);
		DB::table('cities')->insert(['id' => 4117206, 'states_id' => 41, 'name' => 'Nova Olímpia']);
		DB::table('cities')->insert(['id' => 4117214, 'states_id' => 41, 'name' => 'Nova Santa Bárbara']);
		DB::table('cities')->insert(['id' => 4117222, 'states_id' => 41, 'name' => 'Nova Santa Rosa']);
		DB::table('cities')->insert(['id' => 4117255, 'states_id' => 41, 'name' => 'Nova Prata do Iguaçu']);
		DB::table('cities')->insert(['id' => 4117271, 'states_id' => 41, 'name' => 'Nova Tebas']);
		DB::table('cities')->insert(['id' => 4117297, 'states_id' => 41, 'name' => 'Novo Itacolomi']);
		DB::table('cities')->insert(['id' => 4117305, 'states_id' => 41, 'name' => 'Ortigueira']);
		DB::table('cities')->insert(['id' => 4117404, 'states_id' => 41, 'name' => 'Ourizona']);
		DB::table('cities')->insert(['id' => 4117453, 'states_id' => 41, 'name' => 'Ouro Verde do Oeste']);
		DB::table('cities')->insert(['id' => 4117503, 'states_id' => 41, 'name' => 'Paiçandu']);
		DB::table('cities')->insert(['id' => 4117602, 'states_id' => 41, 'name' => 'Palmas']);
		DB::table('cities')->insert(['id' => 4117701, 'states_id' => 41, 'name' => 'Palmeira']);
		DB::table('cities')->insert(['id' => 4117800, 'states_id' => 41, 'name' => 'Palmital']);
		DB::table('cities')->insert(['id' => 4117909, 'states_id' => 41, 'name' => 'Palotina']);
		DB::table('cities')->insert(['id' => 4118006, 'states_id' => 41, 'name' => 'Paraíso do Norte']);
		DB::table('cities')->insert(['id' => 4118105, 'states_id' => 41, 'name' => 'Paranacity']);
		DB::table('cities')->insert(['id' => 4118204, 'states_id' => 41, 'name' => 'Paranaguá']);
		DB::table('cities')->insert(['id' => 4118303, 'states_id' => 41, 'name' => 'Paranapoema']);
		DB::table('cities')->insert(['id' => 4118402, 'states_id' => 41, 'name' => 'Paranavaí']);
		DB::table('cities')->insert(['id' => 4118451, 'states_id' => 41, 'name' => 'Pato Bragado']);
		DB::table('cities')->insert(['id' => 4118501, 'states_id' => 41, 'name' => 'Pato Branco']);
		DB::table('cities')->insert(['id' => 4118600, 'states_id' => 41, 'name' => 'Paula Freitas']);
		DB::table('cities')->insert(['id' => 4118709, 'states_id' => 41, 'name' => 'Paulo Frontin']);
		DB::table('cities')->insert(['id' => 4118808, 'states_id' => 41, 'name' => 'Peabiru']);
		DB::table('cities')->insert(['id' => 4118857, 'states_id' => 41, 'name' => 'Perobal']);
		DB::table('cities')->insert(['id' => 4118907, 'states_id' => 41, 'name' => 'Pérola']);
		DB::table('cities')->insert(['id' => 4119004, 'states_id' => 41, 'name' => 'Pérola d\'Oeste']);
		DB::table('cities')->insert(['id' => 4119103, 'states_id' => 41, 'name' => 'Piên']);
		DB::table('cities')->insert(['id' => 4119152, 'states_id' => 41, 'name' => 'Pinhais']);
		DB::table('cities')->insert(['id' => 4119202, 'states_id' => 41, 'name' => 'Pinhalão']);
		DB::table('cities')->insert(['id' => 4119251, 'states_id' => 41, 'name' => 'Pinhal de São Bento']);
		DB::table('cities')->insert(['id' => 4119301, 'states_id' => 41, 'name' => 'Pinhão']);
		DB::table('cities')->insert(['id' => 4119400, 'states_id' => 41, 'name' => 'Piraí do Sul']);
		DB::table('cities')->insert(['id' => 4119509, 'states_id' => 41, 'name' => 'Piraquara']);
		DB::table('cities')->insert(['id' => 4119608, 'states_id' => 41, 'name' => 'Pitanga']);
		DB::table('cities')->insert(['id' => 4119657, 'states_id' => 41, 'name' => 'Pitangueiras']);
		DB::table('cities')->insert(['id' => 4119707, 'states_id' => 41, 'name' => 'Planaltina do Paraná']);
		DB::table('cities')->insert(['id' => 4119806, 'states_id' => 41, 'name' => 'Planalto']);
		DB::table('cities')->insert(['id' => 4119905, 'states_id' => 41, 'name' => 'Ponta Grossa']);
		DB::table('cities')->insert(['id' => 4119954, 'states_id' => 41, 'name' => 'Pontal do Paraná']);
		DB::table('cities')->insert(['id' => 4120002, 'states_id' => 41, 'name' => 'Porecatu']);
		DB::table('cities')->insert(['id' => 4120101, 'states_id' => 41, 'name' => 'Porto Amazonas']);
		DB::table('cities')->insert(['id' => 4120150, 'states_id' => 41, 'name' => 'Porto Barreiro']);
		DB::table('cities')->insert(['id' => 4120200, 'states_id' => 41, 'name' => 'Porto Rico']);
		DB::table('cities')->insert(['id' => 4120309, 'states_id' => 41, 'name' => 'Porto Vitória']);
		DB::table('cities')->insert(['id' => 4120333, 'states_id' => 41, 'name' => 'Prado Ferreira']);
		DB::table('cities')->insert(['id' => 4120358, 'states_id' => 41, 'name' => 'Pranchita']);
		DB::table('cities')->insert(['id' => 4120408, 'states_id' => 41, 'name' => 'Presidente Castelo Branco']);
		DB::table('cities')->insert(['id' => 4120507, 'states_id' => 41, 'name' => 'Primeiro de Maio']);
		DB::table('cities')->insert(['id' => 4120606, 'states_id' => 41, 'name' => 'Prudentópolis']);
		DB::table('cities')->insert(['id' => 4120655, 'states_id' => 41, 'name' => 'Quarto Centenário']);
		DB::table('cities')->insert(['id' => 4120705, 'states_id' => 41, 'name' => 'Quatiguá']);
		DB::table('cities')->insert(['id' => 4120804, 'states_id' => 41, 'name' => 'Quatro Barras']);
		DB::table('cities')->insert(['id' => 4120853, 'states_id' => 41, 'name' => 'Quatro Pontes']);
		DB::table('cities')->insert(['id' => 4120903, 'states_id' => 41, 'name' => 'Quedas do Iguaçu']);
		DB::table('cities')->insert(['id' => 4121000, 'states_id' => 41, 'name' => 'Querência do Norte']);
		DB::table('cities')->insert(['id' => 4121109, 'states_id' => 41, 'name' => 'Quinta do Sol']);
		DB::table('cities')->insert(['id' => 4121208, 'states_id' => 41, 'name' => 'Quitandinha']);
		DB::table('cities')->insert(['id' => 4121257, 'states_id' => 41, 'name' => 'Ramilândia']);
		DB::table('cities')->insert(['id' => 4121307, 'states_id' => 41, 'name' => 'Rancho Alegre']);
		DB::table('cities')->insert(['id' => 4121356, 'states_id' => 41, 'name' => 'Rancho Alegre D\'Oeste']);
		DB::table('cities')->insert(['id' => 4121406, 'states_id' => 41, 'name' => 'Realeza']);
		DB::table('cities')->insert(['id' => 4121505, 'states_id' => 41, 'name' => 'Rebouças']);
		DB::table('cities')->insert(['id' => 4121604, 'states_id' => 41, 'name' => 'Renascença']);
		DB::table('cities')->insert(['id' => 4121703, 'states_id' => 41, 'name' => 'Reserva']);
		DB::table('cities')->insert(['id' => 4121752, 'states_id' => 41, 'name' => 'Reserva do Iguaçu']);
		DB::table('cities')->insert(['id' => 4121802, 'states_id' => 41, 'name' => 'Ribeirão Claro']);
		DB::table('cities')->insert(['id' => 4121901, 'states_id' => 41, 'name' => 'Ribeirão do Pinhal']);
		DB::table('cities')->insert(['id' => 4122008, 'states_id' => 41, 'name' => 'Rio Azul']);
		DB::table('cities')->insert(['id' => 4122107, 'states_id' => 41, 'name' => 'Rio Bom']);
		DB::table('cities')->insert(['id' => 4122156, 'states_id' => 41, 'name' => 'Rio Bonito do Iguaçu']);
		DB::table('cities')->insert(['id' => 4122172, 'states_id' => 41, 'name' => 'Rio Branco do Ivaí']);
		DB::table('cities')->insert(['id' => 4122206, 'states_id' => 41, 'name' => 'Rio Branco do Sul']);
		DB::table('cities')->insert(['id' => 4122305, 'states_id' => 41, 'name' => 'Rio Negro']);
		DB::table('cities')->insert(['id' => 4122404, 'states_id' => 41, 'name' => 'Rolândia']);
		DB::table('cities')->insert(['id' => 4122503, 'states_id' => 41, 'name' => 'Roncador']);
		DB::table('cities')->insert(['id' => 4122602, 'states_id' => 41, 'name' => 'Rondon']);
		DB::table('cities')->insert(['id' => 4122651, 'states_id' => 41, 'name' => 'Rosário do Ivaí']);
		DB::table('cities')->insert(['id' => 4122701, 'states_id' => 41, 'name' => 'Sabáudia']);
		DB::table('cities')->insert(['id' => 4122800, 'states_id' => 41, 'name' => 'Salgado Filho']);
		DB::table('cities')->insert(['id' => 4122909, 'states_id' => 41, 'name' => 'Salto do Itararé']);
		DB::table('cities')->insert(['id' => 4123006, 'states_id' => 41, 'name' => 'Salto do Lontra']);
		DB::table('cities')->insert(['id' => 4123105, 'states_id' => 41, 'name' => 'Santa Amélia']);
		DB::table('cities')->insert(['id' => 4123204, 'states_id' => 41, 'name' => 'Santa Cecília do Pavão']);
		DB::table('cities')->insert(['id' => 4123303, 'states_id' => 41, 'name' => 'Santa Cruz de Monte Castelo']);
		DB::table('cities')->insert(['id' => 4123402, 'states_id' => 41, 'name' => 'Santa Fé']);
		DB::table('cities')->insert(['id' => 4123501, 'states_id' => 41, 'name' => 'Santa Helena']);
		DB::table('cities')->insert(['id' => 4123600, 'states_id' => 41, 'name' => 'Santa Inês']);
		DB::table('cities')->insert(['id' => 4123709, 'states_id' => 41, 'name' => 'Santa Isabel do Ivaí']);
		DB::table('cities')->insert(['id' => 4123808, 'states_id' => 41, 'name' => 'Santa Izabel do Oeste']);
		DB::table('cities')->insert(['id' => 4123824, 'states_id' => 41, 'name' => 'Santa Lúcia']);
		DB::table('cities')->insert(['id' => 4123857, 'states_id' => 41, 'name' => 'Santa Maria do Oeste']);
		DB::table('cities')->insert(['id' => 4123907, 'states_id' => 41, 'name' => 'Santa Mariana']);
		DB::table('cities')->insert(['id' => 4123956, 'states_id' => 41, 'name' => 'Santa Mônica']);
		DB::table('cities')->insert(['id' => 4124004, 'states_id' => 41, 'name' => 'Santana do Itararé']);
		DB::table('cities')->insert(['id' => 4124020, 'states_id' => 41, 'name' => 'Santa Tereza do Oeste']);
		DB::table('cities')->insert(['id' => 4124053, 'states_id' => 41, 'name' => 'Santa Terezinha de Itaipu']);
		DB::table('cities')->insert(['id' => 4124103, 'states_id' => 41, 'name' => 'Santo Antônio da Platina']);
		DB::table('cities')->insert(['id' => 4124202, 'states_id' => 41, 'name' => 'Santo Antônio do Caiuá']);
		DB::table('cities')->insert(['id' => 4124301, 'states_id' => 41, 'name' => 'Santo Antônio do Paraíso']);
		DB::table('cities')->insert(['id' => 4124400, 'states_id' => 41, 'name' => 'Santo Antônio do Sudoeste']);
		DB::table('cities')->insert(['id' => 4124509, 'states_id' => 41, 'name' => 'Santo Inácio']);
		DB::table('cities')->insert(['id' => 4124608, 'states_id' => 41, 'name' => 'São Carlos do Ivaí']);
		DB::table('cities')->insert(['id' => 4124707, 'states_id' => 41, 'name' => 'São Jerônimo da Serra']);
		DB::table('cities')->insert(['id' => 4124806, 'states_id' => 41, 'name' => 'São João']);
		DB::table('cities')->insert(['id' => 4124905, 'states_id' => 41, 'name' => 'São João do Caiuá']);
		DB::table('cities')->insert(['id' => 4125001, 'states_id' => 41, 'name' => 'São João do Ivaí']);
		DB::table('cities')->insert(['id' => 4125100, 'states_id' => 41, 'name' => 'São João do Triunfo']);
		DB::table('cities')->insert(['id' => 4125209, 'states_id' => 41, 'name' => 'São Jorge d\'Oeste']);
		DB::table('cities')->insert(['id' => 4125308, 'states_id' => 41, 'name' => 'São Jorge do Ivaí']);
		DB::table('cities')->insert(['id' => 4125357, 'states_id' => 41, 'name' => 'São Jorge do Patrocínio']);
		DB::table('cities')->insert(['id' => 4125407, 'states_id' => 41, 'name' => 'São José da Boa Vista']);
		DB::table('cities')->insert(['id' => 4125456, 'states_id' => 41, 'name' => 'São José das Palmeiras']);
		DB::table('cities')->insert(['id' => 4125506, 'states_id' => 41, 'name' => 'São José dos Pinhais']);
		DB::table('cities')->insert(['id' => 4125555, 'states_id' => 41, 'name' => 'São Manoel do Paraná']);
		DB::table('cities')->insert(['id' => 4125605, 'states_id' => 41, 'name' => 'São Mateus do Sul']);
		DB::table('cities')->insert(['id' => 4125704, 'states_id' => 41, 'name' => 'São Miguel do Iguaçu']);
		DB::table('cities')->insert(['id' => 4125753, 'states_id' => 41, 'name' => 'São Pedro do Iguaçu']);
		DB::table('cities')->insert(['id' => 4125803, 'states_id' => 41, 'name' => 'São Pedro do Ivaí']);
		DB::table('cities')->insert(['id' => 4125902, 'states_id' => 41, 'name' => 'São Pedro do Paraná']);
		DB::table('cities')->insert(['id' => 4126009, 'states_id' => 41, 'name' => 'São Sebastião da Amoreira']);
		DB::table('cities')->insert(['id' => 4126108, 'states_id' => 41, 'name' => 'São Tomé']);
		DB::table('cities')->insert(['id' => 4126207, 'states_id' => 41, 'name' => 'Sapopema']);
		DB::table('cities')->insert(['id' => 4126256, 'states_id' => 41, 'name' => 'Sarandi']);
		DB::table('cities')->insert(['id' => 4126272, 'states_id' => 41, 'name' => 'Saudade do Iguaçu']);
		DB::table('cities')->insert(['id' => 4126306, 'states_id' => 41, 'name' => 'Sengés']);
		DB::table('cities')->insert(['id' => 4126355, 'states_id' => 41, 'name' => 'Serranópolis do Iguaçu']);
		DB::table('cities')->insert(['id' => 4126405, 'states_id' => 41, 'name' => 'Sertaneja']);
		DB::table('cities')->insert(['id' => 4126504, 'states_id' => 41, 'name' => 'Sertanópolis']);
		DB::table('cities')->insert(['id' => 4126603, 'states_id' => 41, 'name' => 'Siqueira Campos']);
		DB::table('cities')->insert(['id' => 4126652, 'states_id' => 41, 'name' => 'Sulina']);
		DB::table('cities')->insert(['id' => 4126678, 'states_id' => 41, 'name' => 'Tamarana']);
		DB::table('cities')->insert(['id' => 4126702, 'states_id' => 41, 'name' => 'Tamboara']);
		DB::table('cities')->insert(['id' => 4126801, 'states_id' => 41, 'name' => 'Tapejara']);
		DB::table('cities')->insert(['id' => 4126900, 'states_id' => 41, 'name' => 'Tapira']);
		DB::table('cities')->insert(['id' => 4127007, 'states_id' => 41, 'name' => 'Teixeira Soares']);
		DB::table('cities')->insert(['id' => 4127106, 'states_id' => 41, 'name' => 'Telêmaco Borba']);
		DB::table('cities')->insert(['id' => 4127205, 'states_id' => 41, 'name' => 'Terra Boa']);
		DB::table('cities')->insert(['id' => 4127304, 'states_id' => 41, 'name' => 'Terra Rica']);
		DB::table('cities')->insert(['id' => 4127403, 'states_id' => 41, 'name' => 'Terra Roxa']);
		DB::table('cities')->insert(['id' => 4127502, 'states_id' => 41, 'name' => 'Tibagi']);
		DB::table('cities')->insert(['id' => 4127601, 'states_id' => 41, 'name' => 'Tijucas do Sul']);
		DB::table('cities')->insert(['id' => 4127700, 'states_id' => 41, 'name' => 'Toledo']);
		DB::table('cities')->insert(['id' => 4127809, 'states_id' => 41, 'name' => 'Tomazina']);
		DB::table('cities')->insert(['id' => 4127858, 'states_id' => 41, 'name' => 'Três Barras do Paraná']);
		DB::table('cities')->insert(['id' => 4127882, 'states_id' => 41, 'name' => 'Tunas do Paraná']);
		DB::table('cities')->insert(['id' => 4127908, 'states_id' => 41, 'name' => 'Tuneiras do Oeste']);
		DB::table('cities')->insert(['id' => 4127957, 'states_id' => 41, 'name' => 'Tupãssi']);
		DB::table('cities')->insert(['id' => 4127965, 'states_id' => 41, 'name' => 'Turvo']);
		DB::table('cities')->insert(['id' => 4128005, 'states_id' => 41, 'name' => 'Ubiratã']);
		DB::table('cities')->insert(['id' => 4128104, 'states_id' => 41, 'name' => 'Umuarama']);
		DB::table('cities')->insert(['id' => 4128203, 'states_id' => 41, 'name' => 'União da Vitória']);
		DB::table('cities')->insert(['id' => 4128302, 'states_id' => 41, 'name' => 'Uniflor']);
		DB::table('cities')->insert(['id' => 4128401, 'states_id' => 41, 'name' => 'Uraí']);
		DB::table('cities')->insert(['id' => 4128500, 'states_id' => 41, 'name' => 'Wenceslau Braz']);
		DB::table('cities')->insert(['id' => 4128534, 'states_id' => 41, 'name' => 'Ventania']);
		DB::table('cities')->insert(['id' => 4128559, 'states_id' => 41, 'name' => 'Vera Cruz do Oeste']);
		DB::table('cities')->insert(['id' => 4128609, 'states_id' => 41, 'name' => 'Verê']);
		DB::table('cities')->insert(['id' => 4128625, 'states_id' => 41, 'name' => 'Alto Paraíso']);
		DB::table('cities')->insert(['id' => 4128633, 'states_id' => 41, 'name' => 'Doutor Ulysses']);
		DB::table('cities')->insert(['id' => 4128658, 'states_id' => 41, 'name' => 'Virmond']);
		DB::table('cities')->insert(['id' => 4128708, 'states_id' => 41, 'name' => 'Vitorino']);
		DB::table('cities')->insert(['id' => 4128807, 'states_id' => 41, 'name' => 'Xambrê']);
    }
}
