<?php

use Illuminate\Database\Seeder;

class CitiesTablePBSeeder extends Seeder
{
    /**
     * Alimenta um schema de cities com as cities da Paraíba
     * @author Cesar André (https://github.com/cesar-andre)
     * @return void
     */
    public function run()
    {
    	DB::table('cities')->insert(['id' => 2500106, 'states_id' => 25, 'name' => 'Água Branca']);
		DB::table('cities')->insert(['id' => 2500205, 'states_id' => 25, 'name' => 'Aguiar']);
		DB::table('cities')->insert(['id' => 2500304, 'states_id' => 25, 'name' => 'Alagoa Grande']);
		DB::table('cities')->insert(['id' => 2500403, 'states_id' => 25, 'name' => 'Alagoa Nova']);
		DB::table('cities')->insert(['id' => 2500502, 'states_id' => 25, 'name' => 'Alagoinha']);
		DB::table('cities')->insert(['id' => 2500536, 'states_id' => 25, 'name' => 'Alcantil']);
		DB::table('cities')->insert(['id' => 2500577, 'states_id' => 25, 'name' => 'Algodão de Jandaíra']);
		DB::table('cities')->insert(['id' => 2500601, 'states_id' => 25, 'name' => 'Alhandra']);
		DB::table('cities')->insert(['id' => 2500700, 'states_id' => 25, 'name' => 'São João do Rio do Peixe']);
		DB::table('cities')->insert(['id' => 2500734, 'states_id' => 25, 'name' => 'Amparo']);
		DB::table('cities')->insert(['id' => 2500775, 'states_id' => 25, 'name' => 'Aparecida']);
		DB::table('cities')->insert(['id' => 2500809, 'states_id' => 25, 'name' => 'Araçagi']);
		DB::table('cities')->insert(['id' => 2500908, 'states_id' => 25, 'name' => 'Arara']);
		DB::table('cities')->insert(['id' => 2501005, 'states_id' => 25, 'name' => 'Araruna']);
		DB::table('cities')->insert(['id' => 2501104, 'states_id' => 25, 'name' => 'Areia']);
		DB::table('cities')->insert(['id' => 2501153, 'states_id' => 25, 'name' => 'Areia de Baraúnas']);
		DB::table('cities')->insert(['id' => 2501203, 'states_id' => 25, 'name' => 'Areial']);
		DB::table('cities')->insert(['id' => 2501302, 'states_id' => 25, 'name' => 'Aroeiras']);
		DB::table('cities')->insert(['id' => 2501351, 'states_id' => 25, 'name' => 'Assunção']);
		DB::table('cities')->insert(['id' => 2501401, 'states_id' => 25, 'name' => 'Baía da Traição']);
		DB::table('cities')->insert(['id' => 2501500, 'states_id' => 25, 'name' => 'Bananeiras']);
		DB::table('cities')->insert(['id' => 2501534, 'states_id' => 25, 'name' => 'Baraúna']);
		DB::table('cities')->insert(['id' => 2501575, 'states_id' => 25, 'name' => 'Barra de Santana']);
		DB::table('cities')->insert(['id' => 2501609, 'states_id' => 25, 'name' => 'Barra de Santa Rosa']);
		DB::table('cities')->insert(['id' => 2501708, 'states_id' => 25, 'name' => 'Barra de São Miguel']);
		DB::table('cities')->insert(['id' => 2501807, 'states_id' => 25, 'name' => 'Bayeux']);
		DB::table('cities')->insert(['id' => 2501906, 'states_id' => 25, 'name' => 'Belém']);
		DB::table('cities')->insert(['id' => 2502003, 'states_id' => 25, 'name' => 'Belém do Brejo do Cruz']);
		DB::table('cities')->insert(['id' => 2502052, 'states_id' => 25, 'name' => 'Bernardino Batista']);
		DB::table('cities')->insert(['id' => 2502102, 'states_id' => 25, 'name' => 'Boa Ventura']);
		DB::table('cities')->insert(['id' => 2502151, 'states_id' => 25, 'name' => 'Boa Vista']);
		DB::table('cities')->insert(['id' => 2502201, 'states_id' => 25, 'name' => 'Bom Jesus']);
		DB::table('cities')->insert(['id' => 2502300, 'states_id' => 25, 'name' => 'Bom Sucesso']);
		DB::table('cities')->insert(['id' => 2502409, 'states_id' => 25, 'name' => 'Bonito de Santa Fé']);
		DB::table('cities')->insert(['id' => 2502508, 'states_id' => 25, 'name' => 'Boqueirão']);
		DB::table('cities')->insert(['id' => 2502607, 'states_id' => 25, 'name' => 'Igaracy']);
		DB::table('cities')->insert(['id' => 2502706, 'states_id' => 25, 'name' => 'Borborema']);
		DB::table('cities')->insert(['id' => 2502805, 'states_id' => 25, 'name' => 'Brejo do Cruz']);
		DB::table('cities')->insert(['id' => 2502904, 'states_id' => 25, 'name' => 'Brejo dos Santos']);
		DB::table('cities')->insert(['id' => 2503001, 'states_id' => 25, 'name' => 'Caaporã']);
		DB::table('cities')->insert(['id' => 2503100, 'states_id' => 25, 'name' => 'Cabaceiras']);
		DB::table('cities')->insert(['id' => 2503209, 'states_id' => 25, 'name' => 'Cabedelo']);
		DB::table('cities')->insert(['id' => 2503308, 'states_id' => 25, 'name' => 'Cachoeira dos Índios']);
		DB::table('cities')->insert(['id' => 2503407, 'states_id' => 25, 'name' => 'Cacimba de Areia']);
		DB::table('cities')->insert(['id' => 2503506, 'states_id' => 25, 'name' => 'Cacimba de Dentro']);
		DB::table('cities')->insert(['id' => 2503555, 'states_id' => 25, 'name' => 'Cacimbas']);
		DB::table('cities')->insert(['id' => 2503605, 'states_id' => 25, 'name' => 'Caiçara']);
		DB::table('cities')->insert(['id' => 2503704, 'states_id' => 25, 'name' => 'Cajazeiras']);
		DB::table('cities')->insert(['id' => 2503753, 'states_id' => 25, 'name' => 'Cajazeirinhas']);
		DB::table('cities')->insert(['id' => 2503803, 'states_id' => 25, 'name' => 'Caldas Brandão']);
		DB::table('cities')->insert(['id' => 2503902, 'states_id' => 25, 'name' => 'Camalaú']);
		DB::table('cities')->insert(['id' => 2504009, 'states_id' => 25, 'name' => 'Campina Grande']);
		DB::table('cities')->insert(['id' => 2504033, 'states_id' => 25, 'name' => 'Capim']);
		DB::table('cities')->insert(['id' => 2504074, 'states_id' => 25, 'name' => 'Caraúbas']);
		DB::table('cities')->insert(['id' => 2504108, 'states_id' => 25, 'name' => 'Carrapateira']);
		DB::table('cities')->insert(['id' => 2504157, 'states_id' => 25, 'name' => 'Casserengue']);
		DB::table('cities')->insert(['id' => 2504207, 'states_id' => 25, 'name' => 'Catingueira']);
		DB::table('cities')->insert(['id' => 2504306, 'states_id' => 25, 'name' => 'Catolé do Rocha']);
		DB::table('cities')->insert(['id' => 2504355, 'states_id' => 25, 'name' => 'Caturité']);
		DB::table('cities')->insert(['id' => 2504405, 'states_id' => 25, 'name' => 'Conceição']);
		DB::table('cities')->insert(['id' => 2504504, 'states_id' => 25, 'name' => 'Condado']);
		DB::table('cities')->insert(['id' => 2504603, 'states_id' => 25, 'name' => 'Conde']);
		DB::table('cities')->insert(['id' => 2504702, 'states_id' => 25, 'name' => 'Congo']);
		DB::table('cities')->insert(['id' => 2504801, 'states_id' => 25, 'name' => 'Coremas']);
		DB::table('cities')->insert(['id' => 2504850, 'states_id' => 25, 'name' => 'Coxixola']);
		DB::table('cities')->insert(['id' => 2504900, 'states_id' => 25, 'name' => 'Cruz do Espírito Santo']);
		DB::table('cities')->insert(['id' => 2505006, 'states_id' => 25, 'name' => 'Cubati']);
		DB::table('cities')->insert(['id' => 2505105, 'states_id' => 25, 'name' => 'Cuité']);
		DB::table('cities')->insert(['id' => 2505204, 'states_id' => 25, 'name' => 'Cuitegi']);
		DB::table('cities')->insert(['id' => 2505238, 'states_id' => 25, 'name' => 'Cuité de Mamanguape']);
		DB::table('cities')->insert(['id' => 2505279, 'states_id' => 25, 'name' => 'Curral de Cima']);
		DB::table('cities')->insert(['id' => 2505303, 'states_id' => 25, 'name' => 'Curral Velho']);
		DB::table('cities')->insert(['id' => 2505352, 'states_id' => 25, 'name' => 'Damião']);
		DB::table('cities')->insert(['id' => 2505402, 'states_id' => 25, 'name' => 'Desterro']);
		DB::table('cities')->insert(['id' => 2505501, 'states_id' => 25, 'name' => 'Vista Serrana']);
		DB::table('cities')->insert(['id' => 2505600, 'states_id' => 25, 'name' => 'Diamante']);
		DB::table('cities')->insert(['id' => 2505709, 'states_id' => 25, 'name' => 'Dona Inês']);
		DB::table('cities')->insert(['id' => 2505808, 'states_id' => 25, 'name' => 'Duas Estradas']);
		DB::table('cities')->insert(['id' => 2505907, 'states_id' => 25, 'name' => 'Emas']);
		DB::table('cities')->insert(['id' => 2506004, 'states_id' => 25, 'name' => 'Esperança']);
		DB::table('cities')->insert(['id' => 2506103, 'states_id' => 25, 'name' => 'Fagundes']);
		DB::table('cities')->insert(['id' => 2506202, 'states_id' => 25, 'name' => 'Frei Martinho']);
		DB::table('cities')->insert(['id' => 2506251, 'states_id' => 25, 'name' => 'Gado Bravo']);
		DB::table('cities')->insert(['id' => 2506301, 'states_id' => 25, 'name' => 'Guarabira']);
		DB::table('cities')->insert(['id' => 2506400, 'states_id' => 25, 'name' => 'Gurinhém']);
		DB::table('cities')->insert(['id' => 2506509, 'states_id' => 25, 'name' => 'Gurjão']);
		DB::table('cities')->insert(['id' => 2506608, 'states_id' => 25, 'name' => 'Ibiara']);
		DB::table('cities')->insert(['id' => 2506707, 'states_id' => 25, 'name' => 'Imaculada']);
		DB::table('cities')->insert(['id' => 2506806, 'states_id' => 25, 'name' => 'Ingá']);
		DB::table('cities')->insert(['id' => 2506905, 'states_id' => 25, 'name' => 'Itabaiana']);
		DB::table('cities')->insert(['id' => 2507002, 'states_id' => 25, 'name' => 'Itaporanga']);
		DB::table('cities')->insert(['id' => 2507101, 'states_id' => 25, 'name' => 'Itapororoca']);
		DB::table('cities')->insert(['id' => 2507200, 'states_id' => 25, 'name' => 'Itatuba']);
		DB::table('cities')->insert(['id' => 2507309, 'states_id' => 25, 'name' => 'Jacaraú']);
		DB::table('cities')->insert(['id' => 2507408, 'states_id' => 25, 'name' => 'Jericó']);
		DB::table('cities')->insert(['id' => 2507507, 'states_id' => 25, 'name' => 'João Pessoa']);
		DB::table('cities')->insert(['id' => 2507606, 'states_id' => 25, 'name' => 'Juarez Távora']);
		DB::table('cities')->insert(['id' => 2507705, 'states_id' => 25, 'name' => 'Juazeirinho']);
		DB::table('cities')->insert(['id' => 2507804, 'states_id' => 25, 'name' => 'Junco do Seridó']);
		DB::table('cities')->insert(['id' => 2507903, 'states_id' => 25, 'name' => 'Juripiranga']);
		DB::table('cities')->insert(['id' => 2508000, 'states_id' => 25, 'name' => 'Juru']);
		DB::table('cities')->insert(['id' => 2508109, 'states_id' => 25, 'name' => 'Lagoa']);
		DB::table('cities')->insert(['id' => 2508208, 'states_id' => 25, 'name' => 'Lagoa de Dentro']);
		DB::table('cities')->insert(['id' => 2508307, 'states_id' => 25, 'name' => 'Lagoa Seca']);
		DB::table('cities')->insert(['id' => 2508406, 'states_id' => 25, 'name' => 'Lastro']);
		DB::table('cities')->insert(['id' => 2508505, 'states_id' => 25, 'name' => 'Livramento']);
		DB::table('cities')->insert(['id' => 2508554, 'states_id' => 25, 'name' => 'Logradouro']);
		DB::table('cities')->insert(['id' => 2508604, 'states_id' => 25, 'name' => 'Lucena']);
		DB::table('cities')->insert(['id' => 2508703, 'states_id' => 25, 'name' => 'Mãe d\'Água']);
		DB::table('cities')->insert(['id' => 2508802, 'states_id' => 25, 'name' => 'Malta']);
		DB::table('cities')->insert(['id' => 2508901, 'states_id' => 25, 'name' => 'Mamanguape']);
		DB::table('cities')->insert(['id' => 2509008, 'states_id' => 25, 'name' => 'Manaíra']);
		DB::table('cities')->insert(['id' => 2509057, 'states_id' => 25, 'name' => 'Marcação']);
		DB::table('cities')->insert(['id' => 2509107, 'states_id' => 25, 'name' => 'Mari']);
		DB::table('cities')->insert(['id' => 2509156, 'states_id' => 25, 'name' => 'Marizópolis']);
		DB::table('cities')->insert(['id' => 2509206, 'states_id' => 25, 'name' => 'Massaranduba']);
		DB::table('cities')->insert(['id' => 2509305, 'states_id' => 25, 'name' => 'Mataraca']);
		DB::table('cities')->insert(['id' => 2509339, 'states_id' => 25, 'name' => 'Matinhas']);
		DB::table('cities')->insert(['id' => 2509370, 'states_id' => 25, 'name' => 'Mato Grosso']);
		DB::table('cities')->insert(['id' => 2509396, 'states_id' => 25, 'name' => 'Maturéia']);
		DB::table('cities')->insert(['id' => 2509404, 'states_id' => 25, 'name' => 'Mogeiro']);
		DB::table('cities')->insert(['id' => 2509503, 'states_id' => 25, 'name' => 'Montadas']);
		DB::table('cities')->insert(['id' => 2509602, 'states_id' => 25, 'name' => 'Monte Horebe']);
		DB::table('cities')->insert(['id' => 2509701, 'states_id' => 25, 'name' => 'Monteiro']);
		DB::table('cities')->insert(['id' => 2509800, 'states_id' => 25, 'name' => 'Mulungu']);
		DB::table('cities')->insert(['id' => 2509909, 'states_id' => 25, 'name' => 'Natuba']);
		DB::table('cities')->insert(['id' => 2510006, 'states_id' => 25, 'name' => 'Nazarezinho']);
		DB::table('cities')->insert(['id' => 2510105, 'states_id' => 25, 'name' => 'Nova Floresta']);
		DB::table('cities')->insert(['id' => 2510204, 'states_id' => 25, 'name' => 'Nova Olinda']);
		DB::table('cities')->insert(['id' => 2510303, 'states_id' => 25, 'name' => 'Nova Palmeira']);
		DB::table('cities')->insert(['id' => 2510402, 'states_id' => 25, 'name' => 'Olho d\'Água']);
		DB::table('cities')->insert(['id' => 2510501, 'states_id' => 25, 'name' => 'Olivedos']);
		DB::table('cities')->insert(['id' => 2510600, 'states_id' => 25, 'name' => 'Ouro Velho']);
		DB::table('cities')->insert(['id' => 2510659, 'states_id' => 25, 'name' => 'Parari']);
		DB::table('cities')->insert(['id' => 2510709, 'states_id' => 25, 'name' => 'Passagem']);
		DB::table('cities')->insert(['id' => 2510808, 'states_id' => 25, 'name' => 'Patos']);
		DB::table('cities')->insert(['id' => 2510907, 'states_id' => 25, 'name' => 'Paulista']);
		DB::table('cities')->insert(['id' => 2511004, 'states_id' => 25, 'name' => 'Pedra Branca']);
		DB::table('cities')->insert(['id' => 2511103, 'states_id' => 25, 'name' => 'Pedra Lavrada']);
		DB::table('cities')->insert(['id' => 2511202, 'states_id' => 25, 'name' => 'Pedras de Fogo']);
		DB::table('cities')->insert(['id' => 2511301, 'states_id' => 25, 'name' => 'Piancó']);
		DB::table('cities')->insert(['id' => 2511400, 'states_id' => 25, 'name' => 'Picuí']);
		DB::table('cities')->insert(['id' => 2511509, 'states_id' => 25, 'name' => 'Pilar']);
		DB::table('cities')->insert(['id' => 2511608, 'states_id' => 25, 'name' => 'Pilões']);
		DB::table('cities')->insert(['id' => 2511707, 'states_id' => 25, 'name' => 'Pilõezinhos']);
		DB::table('cities')->insert(['id' => 2511806, 'states_id' => 25, 'name' => 'Pirpirituba']);
		DB::table('cities')->insert(['id' => 2511905, 'states_id' => 25, 'name' => 'Pitimbu']);
		DB::table('cities')->insert(['id' => 2512002, 'states_id' => 25, 'name' => 'Pocinhos']);
		DB::table('cities')->insert(['id' => 2512036, 'states_id' => 25, 'name' => 'Poço Dantas']);
		DB::table('cities')->insert(['id' => 2512077, 'states_id' => 25, 'name' => 'Poço de José de Moura']);
		DB::table('cities')->insert(['id' => 2512101, 'states_id' => 25, 'name' => 'Pombal']);
		DB::table('cities')->insert(['id' => 2512200, 'states_id' => 25, 'name' => 'Prata']);
		DB::table('cities')->insert(['id' => 2512309, 'states_id' => 25, 'name' => 'Princesa Isabel']);
		DB::table('cities')->insert(['id' => 2512408, 'states_id' => 25, 'name' => 'Puxinanã']);
		DB::table('cities')->insert(['id' => 2512507, 'states_id' => 25, 'name' => 'Queimadas']);
		DB::table('cities')->insert(['id' => 2512606, 'states_id' => 25, 'name' => 'Quixabá']);
		DB::table('cities')->insert(['id' => 2512705, 'states_id' => 25, 'name' => 'Remígio']);
		DB::table('cities')->insert(['id' => 2512721, 'states_id' => 25, 'name' => 'Pedro Régis']);
		DB::table('cities')->insert(['id' => 2512747, 'states_id' => 25, 'name' => 'Riachão']);
		DB::table('cities')->insert(['id' => 2512754, 'states_id' => 25, 'name' => 'Riachão do Bacamarte']);
		DB::table('cities')->insert(['id' => 2512762, 'states_id' => 25, 'name' => 'Riachão do Poço']);
		DB::table('cities')->insert(['id' => 2512788, 'states_id' => 25, 'name' => 'Riacho de Santo Antônio']);
		DB::table('cities')->insert(['id' => 2512804, 'states_id' => 25, 'name' => 'Riacho dos Cavalos']);
		DB::table('cities')->insert(['id' => 2512903, 'states_id' => 25, 'name' => 'Rio Tinto']);
		DB::table('cities')->insert(['id' => 2513000, 'states_id' => 25, 'name' => 'Salgadinho']);
		DB::table('cities')->insert(['id' => 2513109, 'states_id' => 25, 'name' => 'Salgado de São Félix']);
		DB::table('cities')->insert(['id' => 2513158, 'states_id' => 25, 'name' => 'Santa Cecília']);
		DB::table('cities')->insert(['id' => 2513208, 'states_id' => 25, 'name' => 'Santa Cruz']);
		DB::table('cities')->insert(['id' => 2513307, 'states_id' => 25, 'name' => 'Santa Helena']);
		DB::table('cities')->insert(['id' => 2513356, 'states_id' => 25, 'name' => 'Santa Inês']);
		DB::table('cities')->insert(['id' => 2513406, 'states_id' => 25, 'name' => 'Santa Luzia']);
		DB::table('cities')->insert(['id' => 2513505, 'states_id' => 25, 'name' => 'Santana de Mangueira']);
		DB::table('cities')->insert(['id' => 2513604, 'states_id' => 25, 'name' => 'Santana dos Garrotes']);
		DB::table('cities')->insert(['id' => 2513653, 'states_id' => 25, 'name' => 'Santarém']);
		DB::table('cities')->insert(['id' => 2513703, 'states_id' => 25, 'name' => 'Santa Rita']);
		DB::table('cities')->insert(['id' => 2513802, 'states_id' => 25, 'name' => 'Santa Teresinha']);
		DB::table('cities')->insert(['id' => 2513851, 'states_id' => 25, 'name' => 'Santo André']);
		DB::table('cities')->insert(['id' => 2513901, 'states_id' => 25, 'name' => 'São Bento']);
		DB::table('cities')->insert(['id' => 2513927, 'states_id' => 25, 'name' => 'São Bentinho']);
		DB::table('cities')->insert(['id' => 2513943, 'states_id' => 25, 'name' => 'São Domingos do Cariri']);
		DB::table('cities')->insert(['id' => 2513968, 'states_id' => 25, 'name' => 'São Domingos de Pombal']);
		DB::table('cities')->insert(['id' => 2513984, 'states_id' => 25, 'name' => 'São Francisco']);
		DB::table('cities')->insert(['id' => 2514008, 'states_id' => 25, 'name' => 'São João do Cariri']);
		DB::table('cities')->insert(['id' => 2514107, 'states_id' => 25, 'name' => 'São João do Tigre']);
		DB::table('cities')->insert(['id' => 2514206, 'states_id' => 25, 'name' => 'São José da Lagoa Tapada']);
		DB::table('cities')->insert(['id' => 2514305, 'states_id' => 25, 'name' => 'São José de Caiana']);
		DB::table('cities')->insert(['id' => 2514404, 'states_id' => 25, 'name' => 'São José de Espinharas']);
		DB::table('cities')->insert(['id' => 2514453, 'states_id' => 25, 'name' => 'São José dos Ramos']);
		DB::table('cities')->insert(['id' => 2514503, 'states_id' => 25, 'name' => 'São José de Piranhas']);
		DB::table('cities')->insert(['id' => 2514552, 'states_id' => 25, 'name' => 'São José de Princesa']);
		DB::table('cities')->insert(['id' => 2514602, 'states_id' => 25, 'name' => 'São José do Bonfim']);
		DB::table('cities')->insert(['id' => 2514651, 'states_id' => 25, 'name' => 'São José do Brejo do Cruz']);
		DB::table('cities')->insert(['id' => 2514701, 'states_id' => 25, 'name' => 'São José do Sabugi']);
		DB::table('cities')->insert(['id' => 2514800, 'states_id' => 25, 'name' => 'São José dos Cordeiros']);
		DB::table('cities')->insert(['id' => 2514909, 'states_id' => 25, 'name' => 'São Mamede']);
		DB::table('cities')->insert(['id' => 2515005, 'states_id' => 25, 'name' => 'São Miguel de Taipu']);
		DB::table('cities')->insert(['id' => 2515104, 'states_id' => 25, 'name' => 'São Sebastião de Lagoa de Roça']);
		DB::table('cities')->insert(['id' => 2515203, 'states_id' => 25, 'name' => 'São Sebastião do Umbuzeiro']);
		DB::table('cities')->insert(['id' => 2515302, 'states_id' => 25, 'name' => 'Sapé']);
		DB::table('cities')->insert(['id' => 2515401, 'states_id' => 25, 'name' => 'Seridó']);
		DB::table('cities')->insert(['id' => 2515500, 'states_id' => 25, 'name' => 'Serra Branca']);
		DB::table('cities')->insert(['id' => 2515609, 'states_id' => 25, 'name' => 'Serra da Raiz']);
		DB::table('cities')->insert(['id' => 2515708, 'states_id' => 25, 'name' => 'Serra Grande']);
		DB::table('cities')->insert(['id' => 2515807, 'states_id' => 25, 'name' => 'Serra Redonda']);
		DB::table('cities')->insert(['id' => 2515906, 'states_id' => 25, 'name' => 'Serraria']);
		DB::table('cities')->insert(['id' => 2515930, 'states_id' => 25, 'name' => 'Sertãozinho']);
		DB::table('cities')->insert(['id' => 2515971, 'states_id' => 25, 'name' => 'Sobrado']);
		DB::table('cities')->insert(['id' => 2516003, 'states_id' => 25, 'name' => 'Solânea']);
		DB::table('cities')->insert(['id' => 2516102, 'states_id' => 25, 'name' => 'Soledade']);
		DB::table('cities')->insert(['id' => 2516151, 'states_id' => 25, 'name' => 'Sossêgo']);
		DB::table('cities')->insert(['id' => 2516201, 'states_id' => 25, 'name' => 'Sousa']);
		DB::table('cities')->insert(['id' => 2516300, 'states_id' => 25, 'name' => 'Sumé']);
		DB::table('cities')->insert(['id' => 2516409, 'states_id' => 25, 'name' => 'Campo de Santana']);
		DB::table('cities')->insert(['id' => 2516508, 'states_id' => 25, 'name' => 'Taperoá']);
		DB::table('cities')->insert(['id' => 2516607, 'states_id' => 25, 'name' => 'Tavares']);
		DB::table('cities')->insert(['id' => 2516706, 'states_id' => 25, 'name' => 'Teixeira']);
		DB::table('cities')->insert(['id' => 2516755, 'states_id' => 25, 'name' => 'Tenório']);
		DB::table('cities')->insert(['id' => 2516805, 'states_id' => 25, 'name' => 'Triunfo']);
		DB::table('cities')->insert(['id' => 2516904, 'states_id' => 25, 'name' => 'Uiraúna']);
		DB::table('cities')->insert(['id' => 2517001, 'states_id' => 25, 'name' => 'Umbuzeiro']);
		DB::table('cities')->insert(['id' => 2517100, 'states_id' => 25, 'name' => 'Várzea']);
		DB::table('cities')->insert(['id' => 2517209, 'states_id' => 25, 'name' => 'Vieirópolis']);
		DB::table('cities')->insert(['id' => 2517407, 'states_id' => 25, 'name' => 'Zabelê']);
    }
}
