<?php

use Illuminate\Database\Seeder;

class CitiesTableMASeeder extends Seeder
{
    /**
     * Alimenta um schema de cities com as cities do Maranhão
     * @author Cesar André (https://github.com/cesar-andre)
     * @return void
     */
    public function run()
    {
    	DB::table('cities')->insert(['id' => 2100055, 'states_id' => 21, 'name' => 'Açailândia']);
		DB::table('cities')->insert(['id' => 2100105, 'states_id' => 21, 'name' => 'Afonso Cunha']);
		DB::table('cities')->insert(['id' => 2100154, 'states_id' => 21, 'name' => 'Água Doce do Maranhão']);
		DB::table('cities')->insert(['id' => 2100204, 'states_id' => 21, 'name' => 'Alcântara']);
		DB::table('cities')->insert(['id' => 2100303, 'states_id' => 21, 'name' => 'Aldeias Altas']);
		DB::table('cities')->insert(['id' => 2100402, 'states_id' => 21, 'name' => 'Altamira do Maranhão']);
		DB::table('cities')->insert(['id' => 2100436, 'states_id' => 21, 'name' => 'Alto Alegre do Maranhão']);
		DB::table('cities')->insert(['id' => 2100477, 'states_id' => 21, 'name' => 'Alto Alegre do Pindaré']);
		DB::table('cities')->insert(['id' => 2100501, 'states_id' => 21, 'name' => 'Alto Parnaíba']);
		DB::table('cities')->insert(['id' => 2100550, 'states_id' => 21, 'name' => 'Amapá do Maranhão']);
		DB::table('cities')->insert(['id' => 2100600, 'states_id' => 21, 'name' => 'Amarante do Maranhão']);
		DB::table('cities')->insert(['id' => 2100709, 'states_id' => 21, 'name' => 'Anajatuba']);
		DB::table('cities')->insert(['id' => 2100808, 'states_id' => 21, 'name' => 'Anapurus']);
		DB::table('cities')->insert(['id' => 2100832, 'states_id' => 21, 'name' => 'Apicum-Açu']);
		DB::table('cities')->insert(['id' => 2100873, 'states_id' => 21, 'name' => 'Araguanã']);
		DB::table('cities')->insert(['id' => 2100907, 'states_id' => 21, 'name' => 'Araioses']);
		DB::table('cities')->insert(['id' => 2100956, 'states_id' => 21, 'name' => 'Arame']);
		DB::table('cities')->insert(['id' => 2101004, 'states_id' => 21, 'name' => 'Arari']);
		DB::table('cities')->insert(['id' => 2101103, 'states_id' => 21, 'name' => 'Axixá']);
		DB::table('cities')->insert(['id' => 2101202, 'states_id' => 21, 'name' => 'Bacabal']);
		DB::table('cities')->insert(['id' => 2101251, 'states_id' => 21, 'name' => 'Bacabeira']);
		DB::table('cities')->insert(['id' => 2101301, 'states_id' => 21, 'name' => 'Bacuri']);
		DB::table('cities')->insert(['id' => 2101350, 'states_id' => 21, 'name' => 'Bacurituba']);
		DB::table('cities')->insert(['id' => 2101400, 'states_id' => 21, 'name' => 'Balsas']);
		DB::table('cities')->insert(['id' => 2101509, 'states_id' => 21, 'name' => 'Barão de Grajaú']);
		DB::table('cities')->insert(['id' => 2101608, 'states_id' => 21, 'name' => 'Barra do Corda']);
		DB::table('cities')->insert(['id' => 2101707, 'states_id' => 21, 'name' => 'Barreirinhas']);
		DB::table('cities')->insert(['id' => 2101731, 'states_id' => 21, 'name' => 'Belágua']);
		DB::table('cities')->insert(['id' => 2101772, 'states_id' => 21, 'name' => 'Bela Vista do Maranhão']);
		DB::table('cities')->insert(['id' => 2101806, 'states_id' => 21, 'name' => 'Benedito Leite']);
		DB::table('cities')->insert(['id' => 2101905, 'states_id' => 21, 'name' => 'Bequimão']);
		DB::table('cities')->insert(['id' => 2101939, 'states_id' => 21, 'name' => 'Bernardo do Mearim']);
		DB::table('cities')->insert(['id' => 2101970, 'states_id' => 21, 'name' => 'Boa Vista do Gurupi']);
		DB::table('cities')->insert(['id' => 2102002, 'states_id' => 21, 'name' => 'Bom Jardim']);
		DB::table('cities')->insert(['id' => 2102036, 'states_id' => 21, 'name' => 'Bom Jesus das Selvas']);
		DB::table('cities')->insert(['id' => 2102077, 'states_id' => 21, 'name' => 'Bom Lugar']);
		DB::table('cities')->insert(['id' => 2102101, 'states_id' => 21, 'name' => 'Brejo']);
		DB::table('cities')->insert(['id' => 2102150, 'states_id' => 21, 'name' => 'Brejo de Areia']);
		DB::table('cities')->insert(['id' => 2102200, 'states_id' => 21, 'name' => 'Buriti']);
		DB::table('cities')->insert(['id' => 2102309, 'states_id' => 21, 'name' => 'Buriti Bravo']);
		DB::table('cities')->insert(['id' => 2102325, 'states_id' => 21, 'name' => 'Buriticupu']);
		DB::table('cities')->insert(['id' => 2102358, 'states_id' => 21, 'name' => 'Buritirana']);
		DB::table('cities')->insert(['id' => 2102374, 'states_id' => 21, 'name' => 'Cachoeira Grande']);
		DB::table('cities')->insert(['id' => 2102408, 'states_id' => 21, 'name' => 'Cajapió']);
		DB::table('cities')->insert(['id' => 2102507, 'states_id' => 21, 'name' => 'Cajari']);
		DB::table('cities')->insert(['id' => 2102556, 'states_id' => 21, 'name' => 'Campestre do Maranhão']);
		DB::table('cities')->insert(['id' => 2102606, 'states_id' => 21, 'name' => 'Cândido Mendes']);
		DB::table('cities')->insert(['id' => 2102705, 'states_id' => 21, 'name' => 'Cantanhede']);
		DB::table('cities')->insert(['id' => 2102754, 'states_id' => 21, 'name' => 'Capinzal do Norte']);
		DB::table('cities')->insert(['id' => 2102804, 'states_id' => 21, 'name' => 'Carolina']);
		DB::table('cities')->insert(['id' => 2102903, 'states_id' => 21, 'name' => 'Carutapera']);
		DB::table('cities')->insert(['id' => 2103000, 'states_id' => 21, 'name' => 'Caxias']);
		DB::table('cities')->insert(['id' => 2103109, 'states_id' => 21, 'name' => 'Cedral']);
		DB::table('cities')->insert(['id' => 2103125, 'states_id' => 21, 'name' => 'Central do Maranhão']);
		DB::table('cities')->insert(['id' => 2103158, 'states_id' => 21, 'name' => 'Centro do Guilherme']);
		DB::table('cities')->insert(['id' => 2103174, 'states_id' => 21, 'name' => 'Centro Novo do Maranhão']);
		DB::table('cities')->insert(['id' => 2103208, 'states_id' => 21, 'name' => 'Chapadinha']);
		DB::table('cities')->insert(['id' => 2103257, 'states_id' => 21, 'name' => 'Cidelândia']);
		DB::table('cities')->insert(['id' => 2103307, 'states_id' => 21, 'name' => 'Codó']);
		DB::table('cities')->insert(['id' => 2103406, 'states_id' => 21, 'name' => 'Coelho Neto']);
		DB::table('cities')->insert(['id' => 2103505, 'states_id' => 21, 'name' => 'Colinas']);
		DB::table('cities')->insert(['id' => 2103554, 'states_id' => 21, 'name' => 'Conceição do Lago-Açu']);
		DB::table('cities')->insert(['id' => 2103604, 'states_id' => 21, 'name' => 'Coroatá']);
		DB::table('cities')->insert(['id' => 2103703, 'states_id' => 21, 'name' => 'Cururupu']);
		DB::table('cities')->insert(['id' => 2103752, 'states_id' => 21, 'name' => 'Davinópolis']);
		DB::table('cities')->insert(['id' => 2103802, 'states_id' => 21, 'name' => 'Dom Pedro']);
		DB::table('cities')->insert(['id' => 2103901, 'states_id' => 21, 'name' => 'Duque Bacelar']);
		DB::table('cities')->insert(['id' => 2104008, 'states_id' => 21, 'name' => 'Esperantinópolis']);
		DB::table('cities')->insert(['id' => 2104057, 'states_id' => 21, 'name' => 'Estreito']);
		DB::table('cities')->insert(['id' => 2104073, 'states_id' => 21, 'name' => 'Feira Nova do Maranhão']);
		DB::table('cities')->insert(['id' => 2104081, 'states_id' => 21, 'name' => 'Fernando Falcão']);
		DB::table('cities')->insert(['id' => 2104099, 'states_id' => 21, 'name' => 'Formosa da Serra Negra']);
		DB::table('cities')->insert(['id' => 2104107, 'states_id' => 21, 'name' => 'Fortaleza dos Nogueiras']);
		DB::table('cities')->insert(['id' => 2104206, 'states_id' => 21, 'name' => 'Fortuna']);
		DB::table('cities')->insert(['id' => 2104305, 'states_id' => 21, 'name' => 'Godofredo Viana']);
		DB::table('cities')->insert(['id' => 2104404, 'states_id' => 21, 'name' => 'Gonçalves Dias']);
		DB::table('cities')->insert(['id' => 2104503, 'states_id' => 21, 'name' => 'Governador Archer']);
		DB::table('cities')->insert(['id' => 2104552, 'states_id' => 21, 'name' => 'Governador Edison Lobão']);
		DB::table('cities')->insert(['id' => 2104602, 'states_id' => 21, 'name' => 'Governador Eugênio Barros']);
		DB::table('cities')->insert(['id' => 2104628, 'states_id' => 21, 'name' => 'Governador Luiz Rocha']);
		DB::table('cities')->insert(['id' => 2104651, 'states_id' => 21, 'name' => 'Governador Newton Bello']);
		DB::table('cities')->insert(['id' => 2104677, 'states_id' => 21, 'name' => 'Governador Nunes Freire']);
		DB::table('cities')->insert(['id' => 2104701, 'states_id' => 21, 'name' => 'Graça Aranha']);
		DB::table('cities')->insert(['id' => 2104800, 'states_id' => 21, 'name' => 'Grajaú']);
		DB::table('cities')->insert(['id' => 2104909, 'states_id' => 21, 'name' => 'Guimarães']);
		DB::table('cities')->insert(['id' => 2105005, 'states_id' => 21, 'name' => 'Humberto de Campos']);
		DB::table('cities')->insert(['id' => 2105104, 'states_id' => 21, 'name' => 'Icatu']);
		DB::table('cities')->insert(['id' => 2105153, 'states_id' => 21, 'name' => 'Igarapé do Meio']);
		DB::table('cities')->insert(['id' => 2105203, 'states_id' => 21, 'name' => 'Igarapé Grande']);
		DB::table('cities')->insert(['id' => 2105302, 'states_id' => 21, 'name' => 'Imperatriz']);
		DB::table('cities')->insert(['id' => 2105351, 'states_id' => 21, 'name' => 'Itaipava do Grajaú']);
		DB::table('cities')->insert(['id' => 2105401, 'states_id' => 21, 'name' => 'Itapecuru Mirim']);
		DB::table('cities')->insert(['id' => 2105427, 'states_id' => 21, 'name' => 'Itinga do Maranhão']);
		DB::table('cities')->insert(['id' => 2105450, 'states_id' => 21, 'name' => 'Jatobá']);
		DB::table('cities')->insert(['id' => 2105476, 'states_id' => 21, 'name' => 'Jenipapo dos Vieiras']);
		DB::table('cities')->insert(['id' => 2105500, 'states_id' => 21, 'name' => 'João Lisboa']);
		DB::table('cities')->insert(['id' => 2105609, 'states_id' => 21, 'name' => 'Joselândia']);
		DB::table('cities')->insert(['id' => 2105658, 'states_id' => 21, 'name' => 'Junco do Maranhão']);
		DB::table('cities')->insert(['id' => 2105708, 'states_id' => 21, 'name' => 'Lago da Pedra']);
		DB::table('cities')->insert(['id' => 2105807, 'states_id' => 21, 'name' => 'Lago do Junco']);
		DB::table('cities')->insert(['id' => 2105906, 'states_id' => 21, 'name' => 'Lago Verde']);
		DB::table('cities')->insert(['id' => 2105922, 'states_id' => 21, 'name' => 'Lagoa do Mato']);
		DB::table('cities')->insert(['id' => 2105948, 'states_id' => 21, 'name' => 'Lago dos Rodrigues']);
		DB::table('cities')->insert(['id' => 2105963, 'states_id' => 21, 'name' => 'Lagoa Grande do Maranhão']);
		DB::table('cities')->insert(['id' => 2105989, 'states_id' => 21, 'name' => 'Lajeado Novo']);
		DB::table('cities')->insert(['id' => 2106003, 'states_id' => 21, 'name' => 'Lima Campos']);
		DB::table('cities')->insert(['id' => 2106102, 'states_id' => 21, 'name' => 'Loreto']);
		DB::table('cities')->insert(['id' => 2106201, 'states_id' => 21, 'name' => 'Luís Domingues']);
		DB::table('cities')->insert(['id' => 2106300, 'states_id' => 21, 'name' => 'Magalhães de Almeida']);
		DB::table('cities')->insert(['id' => 2106326, 'states_id' => 21, 'name' => 'Maracaçumé']);
		DB::table('cities')->insert(['id' => 2106359, 'states_id' => 21, 'name' => 'Marajá do Sena']);
		DB::table('cities')->insert(['id' => 2106375, 'states_id' => 21, 'name' => 'Maranhãozinho']);
		DB::table('cities')->insert(['id' => 2106409, 'states_id' => 21, 'name' => 'Mata Roma']);
		DB::table('cities')->insert(['id' => 2106508, 'states_id' => 21, 'name' => 'Matinha']);
		DB::table('cities')->insert(['id' => 2106607, 'states_id' => 21, 'name' => 'Matões']);
		DB::table('cities')->insert(['id' => 2106631, 'states_id' => 21, 'name' => 'Matões do Norte']);
		DB::table('cities')->insert(['id' => 2106672, 'states_id' => 21, 'name' => 'Milagres do Maranhão']);
		DB::table('cities')->insert(['id' => 2106706, 'states_id' => 21, 'name' => 'Mirador']);
		DB::table('cities')->insert(['id' => 2106755, 'states_id' => 21, 'name' => 'Miranda do Norte']);
		DB::table('cities')->insert(['id' => 2106805, 'states_id' => 21, 'name' => 'Mirinzal']);
		DB::table('cities')->insert(['id' => 2106904, 'states_id' => 21, 'name' => 'Monção']);
		DB::table('cities')->insert(['id' => 2107001, 'states_id' => 21, 'name' => 'Montes Altos']);
		DB::table('cities')->insert(['id' => 2107100, 'states_id' => 21, 'name' => 'Morros']);
		DB::table('cities')->insert(['id' => 2107209, 'states_id' => 21, 'name' => 'Nina Rodrigues']);
		DB::table('cities')->insert(['id' => 2107258, 'states_id' => 21, 'name' => 'Nova Colinas']);
		DB::table('cities')->insert(['id' => 2107308, 'states_id' => 21, 'name' => 'Nova Iorque']);
		DB::table('cities')->insert(['id' => 2107357, 'states_id' => 21, 'name' => 'Nova Olinda do Maranhão']);
		DB::table('cities')->insert(['id' => 2107407, 'states_id' => 21, 'name' => 'Olho d\'Água das Cunhãs']);
		DB::table('cities')->insert(['id' => 2107456, 'states_id' => 21, 'name' => 'Olinda Nova do Maranhão']);
		DB::table('cities')->insert(['id' => 2107506, 'states_id' => 21, 'name' => 'Paço do Lumiar']);
		DB::table('cities')->insert(['id' => 2107605, 'states_id' => 21, 'name' => 'Palmeirândia']);
		DB::table('cities')->insert(['id' => 2107704, 'states_id' => 21, 'name' => 'Paraibano']);
		DB::table('cities')->insert(['id' => 2107803, 'states_id' => 21, 'name' => 'Parnarama']);
		DB::table('cities')->insert(['id' => 2107902, 'states_id' => 21, 'name' => 'Passagem Franca']);
		DB::table('cities')->insert(['id' => 2108009, 'states_id' => 21, 'name' => 'Pastos Bons']);
		DB::table('cities')->insert(['id' => 2108058, 'states_id' => 21, 'name' => 'Paulino Neves']);
		DB::table('cities')->insert(['id' => 2108108, 'states_id' => 21, 'name' => 'Paulo Ramos']);
		DB::table('cities')->insert(['id' => 2108207, 'states_id' => 21, 'name' => 'Pedreiras']);
		DB::table('cities')->insert(['id' => 2108256, 'states_id' => 21, 'name' => 'Pedro do Rosário']);
		DB::table('cities')->insert(['id' => 2108306, 'states_id' => 21, 'name' => 'Penalva']);
		DB::table('cities')->insert(['id' => 2108405, 'states_id' => 21, 'name' => 'Peri Mirim']);
		DB::table('cities')->insert(['id' => 2108454, 'states_id' => 21, 'name' => 'Peritoró']);
		DB::table('cities')->insert(['id' => 2108504, 'states_id' => 21, 'name' => 'Pindaré-Mirim']);
		DB::table('cities')->insert(['id' => 2108603, 'states_id' => 21, 'name' => 'Pinheiro']);
		DB::table('cities')->insert(['id' => 2108702, 'states_id' => 21, 'name' => 'Pio XII']);
		DB::table('cities')->insert(['id' => 2108801, 'states_id' => 21, 'name' => 'Pirapemas']);
		DB::table('cities')->insert(['id' => 2108900, 'states_id' => 21, 'name' => 'Poção de Pedras']);
		DB::table('cities')->insert(['id' => 2109007, 'states_id' => 21, 'name' => 'Porto Franco']);
		DB::table('cities')->insert(['id' => 2109056, 'states_id' => 21, 'name' => 'Porto Rico do Maranhão']);
		DB::table('cities')->insert(['id' => 2109106, 'states_id' => 21, 'name' => 'Presidente Dutra']);
		DB::table('cities')->insert(['id' => 2109205, 'states_id' => 21, 'name' => 'Presidente Juscelino']);
		DB::table('cities')->insert(['id' => 2109239, 'states_id' => 21, 'name' => 'Presidente Médici']);
		DB::table('cities')->insert(['id' => 2109270, 'states_id' => 21, 'name' => 'Presidente Sarney']);
		DB::table('cities')->insert(['id' => 2109304, 'states_id' => 21, 'name' => 'Presidente Vargas']);
		DB::table('cities')->insert(['id' => 2109403, 'states_id' => 21, 'name' => 'Primeira Cruz']);
		DB::table('cities')->insert(['id' => 2109452, 'states_id' => 21, 'name' => 'Raposa']);
		DB::table('cities')->insert(['id' => 2109502, 'states_id' => 21, 'name' => 'Riachão']);
		DB::table('cities')->insert(['id' => 2109551, 'states_id' => 21, 'name' => 'Ribamar Fiquene']);
		DB::table('cities')->insert(['id' => 2109601, 'states_id' => 21, 'name' => 'Rosário']);
		DB::table('cities')->insert(['id' => 2109700, 'states_id' => 21, 'name' => 'Sambaíba']);
		DB::table('cities')->insert(['id' => 2109759, 'states_id' => 21, 'name' => 'Santa Filomena do Maranhão']);
		DB::table('cities')->insert(['id' => 2109809, 'states_id' => 21, 'name' => 'Santa Helena']);
		DB::table('cities')->insert(['id' => 2109908, 'states_id' => 21, 'name' => 'Santa Inês']);
		DB::table('cities')->insert(['id' => 2110005, 'states_id' => 21, 'name' => 'Santa Luzia']);
		DB::table('cities')->insert(['id' => 2110039, 'states_id' => 21, 'name' => 'Santa Luzia do Paruá']);
		DB::table('cities')->insert(['id' => 2110104, 'states_id' => 21, 'name' => 'Santa Quitéria do Maranhão']);
		DB::table('cities')->insert(['id' => 2110203, 'states_id' => 21, 'name' => 'Santa Rita']);
		DB::table('cities')->insert(['id' => 2110237, 'states_id' => 21, 'name' => 'Santana do Maranhão']);
		DB::table('cities')->insert(['id' => 2110278, 'states_id' => 21, 'name' => 'Santo Amaro do Maranhão']);
		DB::table('cities')->insert(['id' => 2110302, 'states_id' => 21, 'name' => 'Santo Antônio dos Lopes']);
		DB::table('cities')->insert(['id' => 2110401, 'states_id' => 21, 'name' => 'São Benedito do Rio Preto']);
		DB::table('cities')->insert(['id' => 2110500, 'states_id' => 21, 'name' => 'São Bento']);
		DB::table('cities')->insert(['id' => 2110609, 'states_id' => 21, 'name' => 'São Bernardo']);
		DB::table('cities')->insert(['id' => 2110658, 'states_id' => 21, 'name' => 'São Domingos do Azeitão']);
		DB::table('cities')->insert(['id' => 2110708, 'states_id' => 21, 'name' => 'São Domingos do Maranhão']);
		DB::table('cities')->insert(['id' => 2110807, 'states_id' => 21, 'name' => 'São Félix de Balsas']);
		DB::table('cities')->insert(['id' => 2110856, 'states_id' => 21, 'name' => 'São Francisco do Brejão']);
		DB::table('cities')->insert(['id' => 2110906, 'states_id' => 21, 'name' => 'São Francisco do Maranhão']);
		DB::table('cities')->insert(['id' => 2111003, 'states_id' => 21, 'name' => 'São João Batista']);
		DB::table('cities')->insert(['id' => 2111029, 'states_id' => 21, 'name' => 'São João do Carú']);
		DB::table('cities')->insert(['id' => 2111052, 'states_id' => 21, 'name' => 'São João do Paraíso']);
		DB::table('cities')->insert(['id' => 2111078, 'states_id' => 21, 'name' => 'São João do Soter']);
		DB::table('cities')->insert(['id' => 2111102, 'states_id' => 21, 'name' => 'São João dos Patos']);
		DB::table('cities')->insert(['id' => 2111201, 'states_id' => 21, 'name' => 'São José de Ribamar']);
		DB::table('cities')->insert(['id' => 2111250, 'states_id' => 21, 'name' => 'São José dos Basílios']);
		DB::table('cities')->insert(['id' => 2111300, 'states_id' => 21, 'name' => 'São Luís']);
		DB::table('cities')->insert(['id' => 2111409, 'states_id' => 21, 'name' => 'São Luís Gonzaga do Maranhão']);
		DB::table('cities')->insert(['id' => 2111508, 'states_id' => 21, 'name' => 'São Mateus do Maranhão']);
		DB::table('cities')->insert(['id' => 2111532, 'states_id' => 21, 'name' => 'São Pedro da Água Branca']);
		DB::table('cities')->insert(['id' => 2111573, 'states_id' => 21, 'name' => 'São Pedro dos Crentes']);
		DB::table('cities')->insert(['id' => 2111607, 'states_id' => 21, 'name' => 'São Raimundo das Mangabeiras']);
		DB::table('cities')->insert(['id' => 2111631, 'states_id' => 21, 'name' => 'São Raimundo do Doca Bezerra']);
		DB::table('cities')->insert(['id' => 2111672, 'states_id' => 21, 'name' => 'São Roberto']);
		DB::table('cities')->insert(['id' => 2111706, 'states_id' => 21, 'name' => 'São Vicente Ferrer']);
		DB::table('cities')->insert(['id' => 2111722, 'states_id' => 21, 'name' => 'Satubinha']);
		DB::table('cities')->insert(['id' => 2111748, 'states_id' => 21, 'name' => 'Senador Alexandre Costa']);
		DB::table('cities')->insert(['id' => 2111763, 'states_id' => 21, 'name' => 'Senador La Rocque']);
		DB::table('cities')->insert(['id' => 2111789, 'states_id' => 21, 'name' => 'Serrano do Maranhão']);
		DB::table('cities')->insert(['id' => 2111805, 'states_id' => 21, 'name' => 'Sítio Novo']);
		DB::table('cities')->insert(['id' => 2111904, 'states_id' => 21, 'name' => 'Sucupira do Norte']);
		DB::table('cities')->insert(['id' => 2111953, 'states_id' => 21, 'name' => 'Sucupira do Riachão']);
		DB::table('cities')->insert(['id' => 2112001, 'states_id' => 21, 'name' => 'Tasso Fragoso']);
		DB::table('cities')->insert(['id' => 2112100, 'states_id' => 21, 'name' => 'Timbiras']);
		DB::table('cities')->insert(['id' => 2112209, 'states_id' => 21, 'name' => 'Timon']);
		DB::table('cities')->insert(['id' => 2112233, 'states_id' => 21, 'name' => 'Trizidela do Vale']);
		DB::table('cities')->insert(['id' => 2112274, 'states_id' => 21, 'name' => 'Tufilândia']);
		DB::table('cities')->insert(['id' => 2112308, 'states_id' => 21, 'name' => 'Tuntum']);
		DB::table('cities')->insert(['id' => 2112407, 'states_id' => 21, 'name' => 'Turiaçu']);
		DB::table('cities')->insert(['id' => 2112456, 'states_id' => 21, 'name' => 'Turilândia']);
		DB::table('cities')->insert(['id' => 2112506, 'states_id' => 21, 'name' => 'Tutóia']);
		DB::table('cities')->insert(['id' => 2112605, 'states_id' => 21, 'name' => 'Urbano Santos']);
		DB::table('cities')->insert(['id' => 2112704, 'states_id' => 21, 'name' => 'Vargem Grande']);
		DB::table('cities')->insert(['id' => 2112803, 'states_id' => 21, 'name' => 'Viana']);
		DB::table('cities')->insert(['id' => 2112852, 'states_id' => 21, 'name' => 'Vila Nova dos Martírios']);
		DB::table('cities')->insert(['id' => 2112902, 'states_id' => 21, 'name' => 'Vitória do Mearim']);
		DB::table('cities')->insert(['id' => 2113009, 'states_id' => 21, 'name' => 'Vitorino Freire']);
		DB::table('cities')->insert(['id' => 2114007, 'states_id' => 21, 'name' => 'Zé Doca']);
    }
}
